spotify/heroic

- heroic-component/src/main/java/com/spotify/heroic/common/Series.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/SuggestBackendKV.java
- Replace our own hashing code
- Change "long hash()" to "String hash()" to make fully use of the new
hash size
> [component,metadata,suggest] use murmur3_128 for series hashcode

- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/BottomKInstance.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/TopKInstance.java
> [aggregation] Add missing jsoncreator in filterk instances

- rpc/nativerpc/src/main/java/com/spotify/heroic/rpc/nativerpc/NativeRpcProtocol.java
> [nativerpcprotocol] fix suggest rpc end points

- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/SuggestBackendKV.java
> [suggest] fix tagValueSuggest

- heroic-component/src/test/java/com/spotify/heroic/aggregation/BucketAggregationTest.java
> [aggregation] fix bucket aggregation test errors

- docs/log4j2-file.xml
- heroic-all/pom.xml
- heroic-all/src/main/java/com/spotify/heroic/HeroicLogging.java
- heroic-all/src/main/java/com/spotify/heroic/profile/ClusterProfile.java
- heroic-dist/pom.xml
- heroic-dist/src/main/java/com/spotify/heroic/HeroicService.java
- heroic-dist/src/main/resources/log4j2.xml
- heroic-shell/src/main/java/com/spotify/heroic/HeroicShell.java
- pom.xml
> introduce and configure jul-to-slf4j and netty to slf4j

- .editorconfig
- .gitignore
Also updated `.gitignore` to mark `.gitignore` itself as important and not
ignored, as well as the new `.editorconfig` file.
> Added EditorConfig file to get indent correct.

- source/_pages/docs/overview.ngt
Adding description per [this request](https://github.com/spotify/heroic/pull/65#issuecomment-238009678) from @udoprog.
> Added a description of Google Cloud Bigtable.

- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/AboveK.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/Aggregations.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/BelowK.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/BottomK.java
@juruen Here is the fix, was not able to get the request mocking up and running yet but it is in progress for API tests.
> [aggregation/simple] fix api regression in filtering aggregations (fixes #79)

- heroic-component/src/main/java/com/spotify/heroic/QueryOptions.java
- heroic-component/src/main/java/com/spotify/heroic/metric/FullQuery.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
- heroic-core/src/main/java/com/spotify/heroic/metric/MetricManagerModule.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractClusterQueryIT.java
- heroic-dist/src/test/java/com/spotify/heroic/HeroicConfigurationTest.java
- heroic-dist/src/test/resources/heroic-metrics-limits.yml
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/AbstractElasticsearchMetadataBackend.java
- heroic-test-it/pom.xml
- heroic-test-it/src/main/java/com/spotify/heroic/test/AbstractMetadataBackendIT.java
- pom.xml
Also add a test to make sure it really does not happen again.
> [all] fix limiting of results (again)

- source/_pages/docs/data_model.ngt
> [docs] fix typo in data model

- source/_pages/docs/api/post-query-batch.ngt
> [docs] Added missing queries parameter to batch endpoint

- .editorconfig
Fix .editorconfig to make it so
> [all] pom.xml files should have 2 space indentation

- heroic-component/src/main/java/com/spotify/heroic/cluster/ClusterShard.java
This requires tiny-async 1.11.0 or later
> [component] Output retry backoff timings in QueryTrace

- docs/rfcs/README.md
Link for document: https://github.com/spotify/heroic/blob/parmus/rfcs/docs/rfcs/README.md
> Added README.md for RFCs

- heroic-component/src/main/java/com/spotify/heroic/common/Statistics.java
- heroic-component/src/main/java/com/spotify/heroic/metric/QueryResult.java
- heroic-component/src/main/java/com/spotify/heroic/metric/QueryResultPart.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/ApiReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopApiReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopHeroicReporter.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-core/src/main/java/com/spotify/heroic/HeroicCore.java
- heroic-core/src/main/java/com/spotify/heroic/metric/MetricManagerModule.java
- heroic-core/src/test/java/com/spotify/heroic/CoreQueryManagerTest.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticApiReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticHeroicReporter.java
New metric sli-query-latency-for-small-queries is a histogram that measures
the latency of queries that have a pre-aggregation sample size of less than
200000. This threshold has been chosen to capture the latency of "small"
queries.
Authors:
* Gabriel Gerhardsson (gabrielgerhardsson)
* Mehrdad Hassan Abadi (mehrdad-hassanabadi)
> New metric: latency of "small" queries

- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/CredentialsBuilder.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/credentials/DefaultCredentialsBuilder.java
- metric/bigtable/src/test/java/com/spotify/heroic/metric/bigtable/credentials/DefaultCredentialsBuilderTest.java
> [metric] Add DefaultCredentialsBuilder

- metric/bigtable/src/test/java/com/spotify/heroic/metric/bigtable/MetricsRowKeySerializerTest.java
> [metric] Use utf-8 in MetricsRowKeySerializerTest

- heroic-test-it/src/main/java/com/spotify/heroic/test/AbstractMetricBackendIT.java
- metric/bigtable/src/test/java/com/spotify/heroic/metric/bigtable/BigtableBackendIT.java
- metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/schema/legacy/LegacySchema.java
- metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/schema/ng/NextGenSchema.java
- metric/datastax/src/test/java/com/spotify/heroic/metric/datastax/AbstractDatastaxBackendIT.java
- metric/datastax/src/test/java/com/spotify/heroic/metric/datastax/LegacyDatastaxBackendIT.java
- metric/datastax/src/test/java/com/spotify/heroic/metric/datastax/NextGenDatastaxBackendIT.java
Related to #213, more tests were enabled when troubleshooting for it.
> Add IT for timestamp alignment issues and enable metric/datastax

- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/ConsumerThread.java
- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/KafkaConsumer.java
No functionality change, only renaming.
> [consumer] Rename a couple of things in ConsumerThread

- heroic-component/src/main/java/com/spotify/heroic/QueryOptions.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
- metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/DatastaxBackend.java
> [component,core,metric/datastax] Fix API regression where .options couldn't be specified

- heroic-all/src/main/java/com/spotify/heroic/profile/BigtableAnalyticsProfile.java
> [all] add credentials=default to BigtableAnalyticsProfile

- heroic-test-it/src/main/java/com/spotify/heroic/test/AbstractSuggestBackendIT.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/SuggestBackendKV.java
Fixing 'Heroic throws NullPointerException if it cannot find ElasticSearch index'
[suggest/elasticsearch, test-it]
Fixing fomatting
> Heroic throws NullPointerException if it cannot find ElasticSearch index

- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/ElasticsearchMetadataModule.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/ElasticsearchSuggestModule.java
Existing functionality: The option writesPerSecond enables a rate limit
of how many writes that may be performed per second. Any additional
write requests will be dropped.
New: This commit adds a possibility to have a slow-start mode for this
rate limit, causing the limit to be 3 times lower for the x first
seconds.
Disabled by deafult. Controlled by the new rateLimitSlowStartSeconds
option for metadata and suggest.
> [elasticsearch] Slow-start mode for rate limiting

- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
Exposed as a statistics entry in the outgoing-response-at-node and incoming-response-from-shard query log entries.
> Show rowsAccessed in query log

- heroic-core/src/main/java/com/spotify/heroic/shell/task/AnalyticsDumpFetchSeries.java
Don't flush for every row.
@udoprog
> [shell] Include full series in AnalyticsDumpFetchSeries

- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/MetricMappingAggregation.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/PointsAboveInstance.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/PointsBelowInstance.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractClusterQueryIT.java
Sets the proper JSONCreator properties on the PointsAbove and PointsBelow instances, which addresses https://github.com/spotify/heroic/issues/351.
> [aggregation] Fix PointsAbove/PointsBelow JSON constructor

- debian/settings.xml
> removed credentials

- .travis.yml
- Dockerfile
- README.md
- run-heroic.sh
This adds a 2 stage docker build/image to Heroic. Travis should proceed as normal and on a merge to master trigger Docker Hub to do the containerized build.
> Dockerfile

- consumer/pubsub/pom.xml
- metric/bigtable/pom.xml
- pom.xml
- rpc/grpc/pom.xml
Update the google-pubsub library and its dependencies to the latest version.
> [core] update google-pubsub library

- heroic-core/src/main/java/com/spotify/heroic/ingestion/IngestionModule.java
- heroic-dist/src/main/java/com/spotify/heroic/Parameters.kt
two commits to fix some issues when moving everything to kotlin.
@hexedpackets @lmuhlha
> fix startup issues

- build.gradle
- example/heroic.example.yml
- heroic-component/build.gradle
- heroic-core/build.gradle
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-core/src/main/java/com/spotify/heroic/HeroicCore.java
- heroic-core/src/main/java/com/spotify/heroic/http/query/QueryResource.java
- heroic-core/src/main/java/com/spotify/heroic/http/tracing/TextFormatGetter.java
- heroic-core/src/test/java/com/spotify/heroic/http/tracing/TextFormatGetterTest.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
- rpc/grpc/src/main/java/com/spotify/heroic/rpc/grpc/GrpcRpcClient.java
- Autovalue import was missing for EnvironmentMetadata
- Handle Text Format Getter null pointer exception
- Update config example
- Tracing code clean up
- Link Query Resource spans
- Lightstep should be configured to load balance correctly
- Update gradle dependencies
> Tracing bug fixes

- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/Spotify100.java
Close span to prevent mem leaks
> [core] Close span

- build.gradle
This resolves several CVEs around Jetty 9.4.x
> Update jetty version.

- heroic-core/src/main/java/com/spotify/heroic/HeroicConfig.java
> [core] Remove unused disableMetrics option.

- docs/_layouts/fault-tree.html
The URLs got missed when merging in changes from other PRs.
> [docs] Fix relative URLs in fault tree docs.

- heroic-component/src/main/java/com/spotify/heroic/statistics/ConsumerReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopConsumerReporter.java
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/Spotify100.java
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/Spotify100Proto.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticConsumerReporter.java
- Add batch size metrics by consumers
> Metrics size

- docs/_includes/fields/post-query-metrics/filter.html
- docs/content/_api_types/filter.md
> Fix broken filter links in documentation.

- consumer/kafka/build.gradle
- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/Connection.java
- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/ConsumerThread.java
- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/KafkaConsumerModule.java
- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/RealKafkaConnection.java
> [kafka] Remove lombok from kafka consumer.

- discovery/simple/build.gradle
- discovery/simple/src/main/java/com/spotify/heroic/cluster/discovery/simple/SrvRecordDiscoveryModule.java
- discovery/simple/src/main/java/com/spotify/heroic/cluster/discovery/simple/StaticListDiscoveryModule.java
AFAICT the `@Data` annotation wasn't even providing any value to these classes.
> [discovery-simple] Remove lombok from discovery module.

- .travis.yml
- Dockerfile
- README.md
- build.gradle
- docs/content/_docs/getting_started/compile.html
- gradlew
> Update dependencies to support Java 9+.

- docs/content/_docs/aggregations.html
- docs/content/_docs/data_model.html
- docs/content/_docs/query_language.html
Also remove outdated events docs
> Add resource identifiers to aggregation docs

- docs/content/_docs/data_model.html
- docs/content/_docs/federation.html
- docs/content/_docs/getting_started/index.html
- docs/content/_docs/overview.html
- docs/content/_docs/visualizations.html
- docs/index.html
And a bunch of generic fixes & link updates
> [docs] Define resource identifiers, add visualization section

- docs/content/_docs/config.md
- heroic-core/src/main/java/com/spotify/heroic/cluster/ClusterManagerModule.java
- heroic-core/src/main/java/com/spotify/heroic/cluster/CoreClusterManager.java
- usage-tracking/google/src/main/java/com/spotify/heroic/usagetracking/google/GoogleAnalytics.kt
> [usagetracking] Send an uptime event every 24 hours.

- build.gradle
> Fallback to DOCKER_TAG when setting version.

- usage-tracking/google/src/main/java/com/spotify/heroic/usagetracking/google/GoogleAnalytics.kt
Without setting a timeout these calls could block forever with network issues.
Without closing the resource resources will be leaked (saw some warnings in the logs about this)
> [usage-tracking] set timeout and close body

- docs/_includes/requests/metadata-tagkey-count.json
- docs/_includes/responses/post-metadata-tagkey-count.json
- docs/content/_endpoints/post-metadata-tagkey-count.md
> add docs for metadata/tagkey-count

- docs/content/_docs/config.md
Fix the reference to the example config that was changed in #597
> Fix example link.

- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/Connection.java
> [elasticsearch] Set order for templates to 100.

- build.gradle
- heroic-component/src/main/java/com/spotify/heroic/metric/NodeError.kt
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/Connection.java
- heroic-test/src/main/java/com/spotify/heroic/test/AbstractSuggestBackendIT.java
- heroic-test/src/test/java/com/spotify/heroic/suggest/elasticsearch/SuggestBackendKVIT.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/SuggestBackendKV.java
- suggest/memory/src/test/java/com/spotify/heroic/suggest/memory/MemoryBackendIT.java
bulk writes are supposed to reduce overhead and increase indexing speed.
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html
> [suggest-elasticsearch] write series and tags in bulk

- docs/content/_docs/aggregations.html
> Document points above/below aggregations.

- docs/content/_endpoints/post-query-metrics.md
- Features Configuration link is broken on https://spotify.github.io/heroic/docs/api/post-query-metrics
> Update broken features link

- docs/content/_docs/config.md
> add some docs on limits
