spotify/heroic

- heroic-component/src/main/java/com/spotify/heroic/QueryStateException.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-core/src/main/java/com/spotify/heroic/HeroicServer.java
- heroic-core/src/main/java/com/spotify/heroic/common/CoreJavaxRestFramework.java
- heroic-core/src/main/java/com/spotify/heroic/filter/FilterJsonDeserializerImpl.java
- heroic-core/src/main/java/com/spotify/heroic/http/ExceptionExceptionMapper.java
- heroic-core/src/main/java/com/spotify/heroic/http/HeroicResource.java
- heroic-core/src/main/java/com/spotify/heroic/http/InternalErrorMessage.java
- heroic-core/src/main/java/com/spotify/heroic/http/JsonErrorMessage.java
- heroic-core/src/main/java/com/spotify/heroic/http/JsonMappingExceptionMapper.java
- heroic-core/src/main/java/com/spotify/heroic/http/JsonParseErrorMessage.java
- heroic-core/src/main/java/com/spotify/heroic/http/JsonParseExceptionMapper.java
- heroic-core/src/main/java/com/spotify/heroic/http/Module.java
- heroic-core/src/main/java/com/spotify/heroic/http/ParseErrorMessage.java
- heroic-core/src/main/java/com/spotify/heroic/http/QueryStateExceptionMapper.java
* Guarantee that errors are JSON                                                                                                                             
* Include .path describing where a structural error is when returning 400 (and                                                                               
type is "json-error").                                                                                                                                     
* Disable default plain/text error mappers that come w/ fasterxml.                                                                                           
New error types are:                                                                                                                                         
* …
> [core] convert internal Jetty errors to JSON

- heroic-shell/src/main/java/com/spotify/heroic/shell/QuoteParser.java
These have leading spaces
I was going to add a test case, but I wasn't positive on how the syntax of QuoteParserTest works.
Would this work?
```
test(Case.of("  trimming_spaces  ", "trimming_spaces"));
```
> Trim white space around shell input

- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/BottomK.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/BottomKInstance.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/FilterKAggregationBuilder.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/FilterKInstance.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/FilterKInstanceImpl.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/FilterKSerializer.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/Module.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/TopK.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/TopKInstance.java
- aggregation/simple/src/test/java/com/spotify/heroic/aggregation/simple/FilterKAggregationTest.java
This aggregation provides topk and bottomk filtering. Time-series are
sorted by computing the area under the curve.
It needs to be used along with a child aggregation.
e.g: "topk(3, avergage by host)"
> Add support for FilterK aggregations

- source/_pages/docs/getting_started/compile.ngt
only shaded version of jar could be executed without additional classpath locations
> use shaded version of heroic jar

- source/_pages/docs/getting_started/installation.ngt
Current version of Heroic (at least heroic-shell -P cassandra -X cassandra.seeds=<seeds> -X cassandra.configure) doesn't work with Cassandra 3, so declare correct version in dependencies.
> declare required Cassandra version

- source/_pages/docs/api.ngt
[docs] update /query/metrics example
Make the example request to /query/metrics have an explicit unit and value.
The value needs to be set in the example query, I'll update the error
message to be more specific than just returning "value" for the failure.
```
curl -H "Content-Type: application/json" http://localhost:8080/query/metrics -d '
{"range": {"type":"relative"}, "filter": ["and", ["key", "foo"], ["=", "foo", "bar"], ["+", "role"]], "groupBy": ["site"]}'
{
"type": "json-error"
"path":"range",
"status":400,
"reason":"Bad Request",
"message":"Instantiation of [simple type, class com.spotify.heroic.QueryDateRange$Relative] value failed: value",
}
```
Also having an empty aggregator being applied to an empty result set
causes an error. I chose to remove this query option instead.
``` …
```
> [docs] update /query/metrics example

- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableMetricModule.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/CustomStringSerializer.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/MetricsRowKeySerializer.java
- metric/bigtable/src/test/java/com/spotify/heroic/metric/bigtable/MetricsRowKeySerializerTest.java
- pom.xml
- Upgrade tiny-serializer to 1.4.5 to configure string serialization
- Add custom string serializer to honour prevous serialization
> [bigtable] make serialization backwards compatible

- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/AboveK.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/BelowK.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/BottomK.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/TopK.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/Aggregation.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/Chain.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/Collapse.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/Empty.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/Group.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/Options.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/SamplingAggregation.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
This simplifies the Aggregation interface by removing the initial cadence hint.
This hint is not necessary since the final cadence can be extracted from the
`AggregationInstance` which takes the initial range-based cadence into account
as a hint.
This does slightly change the behavior of queries which specifies no resolution in part of their aggregations, 
This does slightly change the behaviour of queries like: `sum(10m) | average`, after this change average will use the resolution derived from the range, rather than the previous aggregation. I believe this behaviour is more expected.
> [all] remove cadence hint in Aggregation

- README.md
Looks like ClusterIT was renamed to ClusterQueryIT in 866882f.
> fix link to integration test example

- README.md
When viewing https://github.com/spotify/heroic, Github renders the links
to `idea` and `eclipse` as links to `https://github.com/spotify/idea`
etc. Fix this by linking to the README instead.
> fix links to idea/eclipse directories

- heroic-parser/src/main/antlr4/com/spotify/heroic/grammar/HeroicQuery.g4
- heroic-parser/src/test/java/com/spotify/heroic/grammar/QueryParserTest.java
This changes the precedence of the `SimpleString` lexer rule to happen after
`Integer`, `Float`, and `Duration`.
It also allows `SimpleString` to start with a numeric component, but because of
the change in precedence the above will match before if applicable.
This allows the following expression to work (as referenced in #76):
```
$key = 4cf41d4b-a5d2-420e-b008-644f0b3d7832
```
> [parser] relax SimpleString and fix precedence (fixes #76)

- heroic-shell/src/main/java/com/spotify/heroic/HeroicShell.java
This addresses the problem referenced in #70 .  Please let me know if you have any questions or suggestions.  
Note: I enclosed `core.shutdown()` within a `finally` block to ensure it always runs as it currently does.   That method is currently empty but I assume that its functionality will be implemented.
> HeroicShell should return exit code 1 in case of errors

- .travis.yml
findbugs support adds an extra 10 minutes, keep it disabled for now.
> [travis] only test master branch and disable findbugs

- heroic-dist/pom.xml
This will disable shading for `dist` when `environment=test` is specified which is specifically designed for running all available test suites, and shading should be an unnecessary step.
This will not affect regular packaging builds (`mvn clean package`).
This build should give an indication how how faster testing will be without this step.
> [dist] skip shading when environment=test

- heroic-core/src/main/java/com/spotify/heroic/shell/task/ParseQuery.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/Pause.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/TestPrint.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/TestReadFile.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractLocalClusterIT.java
- heroic-dist/src/test/java/com/spotify/heroic/ClusterQueryIT.java
- heroic-dist/src/test/java/com/spotify/heroic/TaskIT.java
`AbstractLocalClusterIT` has been modified to bee less opinionated and is now used to setup integration tests for a few basic tasks.
> [core,dist] implement integration tests for tasks

- pom.xml
- reporting/README.md
- reporting/pom.xml
codecov only looks at `jacoco.xml` files generated by reports when determining total coverage. These only contain coverage as reported per-module and ignores if one module tests aspects of another.
This is solved by introducing a `reporting` module that depends immediately on everything that should be included in the coverage and using the `report-aggregate` goal of jacoco which specifically merges all immediate dependencies into a single report.
> [pom] introduce reporting module to do aggregate reporting

- .travis.yml
- heroic-component/src/main/java/com/spotify/heroic/Query.java
- heroic-component/src/main/java/com/spotify/heroic/QueryBuilder.java
- heroic-component/src/main/java/com/spotify/heroic/common/Feature.java
- heroic-component/src/main/java/com/spotify/heroic/common/FeatureSet.java
- heroic-component/src/main/java/com/spotify/heroic/common/Features.java
- heroic-component/src/test/java/com/spotify/heroic/common/FeatureSetTest.java
- heroic-component/src/test/java/com/spotify/heroic/common/FeaturesTest.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-core/src/main/java/com/spotify/heroic/HeroicConfig.java
- heroic-core/src/main/java/com/spotify/heroic/dagger/PrimaryModule.java
- heroic-core/src/main/java/com/spotify/heroic/http/query/QueryMetrics.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractClusterQueryIT.java
- pom.xml
Enable `shift_range` by default.
Add a `disabled` field to query and configuration which will cause the specified feature to be disabled for that query.
Clarify that features should be named to be enabled (not disabled) to avoid future complexity.
This could also be implemented so that the set of features is specified using operators as prefix, like:
Features are applied in the following order:
`(((default_features + configuration_features) - configuration_disabled) + query_features) - query_disabled`
`+` being joining two sets and `-` means subtracting the right hand side set from the left hand side.
```javascript
{
/* query */,
"features": [
"com.spotify.heroic.bar"
],
"disabled": [
"com.spotify.heroic.baz"
]
}
```
```yaml
features:
- com.spotify.heroic.bar
disabled:
- …
```
> [component,core] enable shift_range by default and allow disabling of features

- heroic-core/src/main/java/com/spotify/heroic/HeroicCore.java
- heroic-core/src/main/java/com/spotify/heroic/dagger/LoadingModule.java
- heroic-dist/src/test/java/com/spotify/heroic/HeroicConfigurationTest.java
This fixes a startup regression introduced in 5094210.
The issue was caused by the internal started future never being resolved, which prevents the initial cluster refresh from being called as is done here:
https://github.com/spotify/heroic/blob/master/heroic-core/src/main/java/com/spotify/heroic/cluster/CoreClusterManager.java#L306
> [core] actually start the internal life cycles and test it

- statistics/semantic/pom.xml
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetadataBackendReporter.java
- statistics/semantic/src/test/java/com/spotify/heroic/statistics/semantic/SemanticMetadataBackendReporterTest.java
Currently if a statistics module is configured the `metadata-find-series` and `metadata-find-series-ids` tasks will return empty results.
These tasks use these methods, which were currently not implemented in the decorating class.
I've added the forwarding, and test-cases to make sure that all defender methods have the correct implementation.
> [statistics/semantic] fix forwarding of method calls in decorated type

- heroic-core/src/main/java/com/spotify/heroic/HeroicCore.java
- heroic-core/src/main/java/com/spotify/heroic/dagger/LoadingModule.java
Executors provided through configuration should not be stopped by `HeroicCore`.
This _hopefully_ fixes the issue that arises here:
https://travis-ci.org/spotify/heroic/builds/166443596#L2305
Note the `java.util.concurrent.RejectedExecutionException`.
Because we use a shared thread pool for some of the tests here:
https://github.com/spotify/heroic/blob/master/heroic-dist/src/test/java/com/spotify/heroic/AbstractLocalClusterIT.java#L30
This is where it is being provided:
https://github.com/spotify/heroic/blob/master/heroic-dist/src/test/java/com/spotify/heroic/AbstractLocalClusterIT.java#L168
Really hard to know if this works or not since it is timing-related (failsafe plugin runs things in parallel).
> [core] do not shutdown executors provided externally

- heroic-core/src/main/java/com/spotify/heroic/shell/ShellServerModule.java
- heroic-dist/src/test/java/com/spotify/heroic/HeroicConfigurationTest.java
- heroic-dist/src/test/resources/heroic-null-shell-host.yml
An absent value in `shellServer.host` causes the following exception:
```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: hostname can't be null
```
This fixes that issue and adds a test to check for it.
> [core,dist] fix ShellServerModule configuration when host is empty

- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/AboveKInstance.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/BelowKInstance.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/BottomKInstance.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/FilterAggregation.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/TopKInstance.java
- aggregation/simple/src/test/java/com/spotify/heroic/aggregation/simple/FilterAggregationTest.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractClusterQueryIT.java
Also add tests that performs a non-distributed filtering aggregation, and checks that serialization works as expected.
There are some duplicated infrastructure in the test that should be moved into `heroic-test-base`, specifically we want to be able to load serializers using a `LoadingComponent` to avoid repeating that piece of initialization all the time. `HeroicMappers` also needs a new home in that case.
> [aggregation/simple,dist] fix test so that non-distributed filtering aggregations work

- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/AbstractElasticsearchMetadataBackend.java
- heroic-elasticsearch-utils/src/test/java/com/spotify/heroic/elasticsearch/ScrollTransformTest.java
ScrollTransform<T> have a number of minor bugs:
- Duplicates count towards to limit making the actual result unpredictable
- Limit check is off-by-one
- If the number of results is exactly one more than the limit, isLimited is incorrectly set to false, because the limit check happens in the beginning of the loop
This patch addresses all of the above.
> Fix ScrollTransform<T>

- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/Delta.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/DeltaInstance.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/Module.java
- aggregation/simple/src/test/java/com/spotify/heroic/aggregation/simple/DeltaTest.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractClusterQueryIT.java
Adds delta aggregation (i.e. "diff" in KairosDB or "rate" in OpenTSDB; open to alternative names). There are no arguments, leaving it up to the user to decide whether to chain it as an input to a `SamplingAggregation`, or to diff the output for any other `Aggregation`. Example:
```
{
"range": {"type": "relative", "unit": "HOURS", "value": 2},
"filter": ["and", ["key", "foo"], ["=", "foo", "bar"], ["+", "role"]],
"aggregation": {"type": "delta"},
"groupBy": ["site"]
}
```
The above would return the difference of each point from the last within the sample. ~~The first point in a difference is always 0.~~ (EDIT: The First point sampled is truncated and the first _returned_ point is the difference from the last point).
This is my first time writing Java, so please go easy! I understand it …
> Delta aggregation

- heroic-component/src/main/java/com/spotify/heroic/statistics/IngestionManagerReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopIngestionManagerReporter.java
- heroic-core/src/main/java/com/spotify/heroic/ingestion/CoreIngestionGroup.java
- heroic-core/src/test/java/com/spotify/heroic/ingestion/CoreIngestionGroupTest.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticIngestionManagerReporter.java
Report dropped-by-filter when a filter drops a time series during ingest. This fixes a "XXX:" comment.
Also updated tests.
> Report when a time series is filtered out during ingest, try#2

- metric/bigtable/pom.xml
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/api/Table.java
- repackaged/bigtable/pom.xml
Bigtable client library 0.9.4 downgraded protobuf as well, which is why getColumnFamiliesMap() change to getColumnFamilies()
> Bumped Bigtable client library to 0.9.4

- metric/bigtable/src/main/java/com/spotify/heroic/analytics/bigtable/BigtableAnalyticsModule.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableConnectionBuilder.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableMetricModule.java
Allow a new setting for bigtable metric backend: batchSize.
This will set the size of BulkMutations when initializing BigTable.
> Set Bigtable batchSize as a parameter

- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticFutureReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/Units.java
This adds pending counters to instrumented futures.
The pending counter is incremented when the future is created, and decremented when it finishes. This gives an indication of how many pending operations there are for a given type of future.
> [statistics/semantic] add pending counter

- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/FilterKAreaStrategy.java
- aggregation/simple/src/test/java/com/spotify/heroic/aggregation/simple/FilterKAreaStrategyTest.java
Metrics with 0 data points (e.g. time series, which are no longer reported but still in the index) should not be considered for TopK and BottomK.
> [aggregations] Filter out time series with 0 datapoints in TopK/BottomK

- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableBackend.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/api/BigtableDataClient.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/api/BigtableDataClientImpl.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/api/RowFilter.java
This PR improves the Bigtable backend a bit.
- Using readFlatRowsAsync() instead of readRowsAsync() avoid a bunch of unnecessary intermediate objects and sorting. This should lower memory usage and GC pressure.
- Count the actual datapoints rather than just the rows.
> [metric/bigtable] Use readFlatRowsAsync() and fix quota

- heroic-dist/src/test/java/com/spotify/heroic/AbstractLocalClusterIT.java
- rpc/grpc/src/main/java/com/spotify/heroic/rpc/grpc/GrpcRpcProtocolModule.java
Also relates to #142 
Port number as suggested by @zfrank
> [rpc/grpc] use 9698 as a default port (fixes #139, #111)

- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/FilterPointsThresholdStrategy.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/MetricMappingAggregation.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/MetricMappingStrategy.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/Module.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/PointsAbove.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/PointsAboveInstance.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/PointsBelow.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/PointsBelowInstance.java
- aggregation/simple/src/test/java/com/spotify/heroic/aggregation/simple/FilterPointsThresholdStrategyTest.java
- aggregation/simple/src/test/java/com/spotify/heroic/aggregation/simple/PointsAboveInstanceTest.java
- aggregation/simple/src/test/java/com/spotify/heroic/aggregation/simple/PointsBelowInstanceTest.java
The `pointsabove` and `pointsbelow` aggregations work similar to the `abovek` and `belowk` aggregations, except they act on a per-point basis, rather than a per-series basis. The use case we have for this is a follows:
- A metric comes from our devices, incrementing over time and occasionally resetting.
- We want to sum all of the positive deltas (effectively ignoring the resets), so as to get the total "forward progress" of the metric over a given time period.
Our aggregations look something like this (tested on real data in our QA BigTable cluster and confirmed working):
```
"aggregation": {
"type": "chain",
"chain": [
{"type": "delta"},
{"type": "pointsabove", "k": 0},
{"type": "sum", "sampling": {"size": "1h"}}
]
}
```
> [aggregation] PointsAbove and PointsBelow

- heroic-component/src/main/java/com/spotify/heroic/metric/FetchQuotaWatcher.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/DataInMemoryReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopMetricBackendReporter.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
- heroic-core/src/test/java/com/spotify/heroic/metric/LocalMetricManagerTest.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetricBackendReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/Units.java
New counters:
1) sample-size-live:
Incremented on data being read from backend.
Decremented when processing of data is done, i.e. when it is expected that data is freed.
2) sample-size-accumulated:
Incremented on data being read from backend.
Decremented when the whole request finishes.
Also started adding test scaffolding for LocalMetricManagerTest. It's too much work to do the full test at this time, but here's at least the test scaffolding.
> [component, core, statistics] Add counters for tracking samples in mem

- .travis.yml
- pom.xml
Travis only provides two threads, this attempts to make sure we only use two threads and retain sensible defaults when building outside of Travis.
> [travis,pom] tweak build configuration to optimize thread usage

- heroic-core/src/main/java/com/spotify/heroic/dagger/LoadingModule.java
This change affects the shutdown behaviour of core ScheduledExecutorService so that it doesn't wait for scheduled/delayed tasks that aren't yet running but are scheduled to run at some time in the future. Previous to this the cluster refresh in clustered configurations would always be waited upon, introducing a delay in the shutdown.
> [core] Faster shutdown of Heroic

- heroic-component/src/main/java/com/spotify/heroic/metric/QueryTrace.java
- heroic-component/src/main/java/com/spotify/heroic/metric/Tracing.java
- heroic-component/src/test/java/com/spotify/heroic/metric/QueryTraceTest.java
- heroic-component/src/test/java/com/spotify/heroic/metric/TracingTest.java
This change introduces the `Tracing` type and extends the capabilities of `QueryTrace`.
The new `Tracing` type encapsulated if tracing is enabled or not. And when tracing is disabled, performs no-ops in place of the actual tracing operations.
Consider the following example:
``` java
public QueryTrace tracedMethod() {
final Tracing tracing = Tracing.fromBoolean(true);
final QueryTrace.NamedWatch parentWatch = tracing.watch(QueryTrace.identifier("parent"));
final QueryTrace.Joiner parentJoiner = parentWatch.joiner();
{
final QueryTrace.NamedWatch childWatch = parentWatch.watch(QueryTrace.identifier("one"));
/* do something that takes time */
parentJoiner.addChild(childWatch.end());
}
{
final QueryTrace.NamedWatch childWatch = parentWatch.watch(QueryTrace.identifier("two"));
/* do something …
```
> Improved Tracing Framework

- heroic-core/src/main/java/com/spotify/heroic/dagger/LoadingModule.java
This makes DelayedCollectCoordinator able to handle when there's many AsyncFuture's linked that are immediately resolved. Previous to this change, that scenario would result in a stack overflow.
This requires tiny-async 1.11.0, which we just switched to.
> [core] Use the new recursion safety feature in tiny-async

- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/ConsumerThread.java
- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/KafkaConsumerModule.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/ConsumerReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopConsumerReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticConsumerReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticRatioGauge.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/Units.java
The new metric is of type "ratio" (added in this commit), and named
"consumer-threads-live-ratio". In normal operation it should always be 1.
Anything below 1 (except during startup), is likely a good basis for signalling
an alert.
> [all] Add metric for ratio of live Kafka ConsumerThread's

- heroic-component/src/main/java/com/spotify/heroic/statistics/ApiReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopApiReporter.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticApiReporter.java
Adds a set of new metrics, measuring a full query on the API node level. this
differs from query-metrics-* in that those metrics are on the data node level
while this is on the API node level.
* query-latency
* query-failure-rate
* query-resolve-rate
* query-cancel-rate
* query-pending
> [component, core, statistics] Add query metrics

- heroic-component/src/main/java/com/spotify/heroic/async/AsyncObservable.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractClusterQueryIT.java
- heroic-test-it/src/main/java/com/spotify/heroic/test/AbstractMetricBackendIT.java
- heroic-test-it/src/main/java/com/spotify/heroic/test/Events.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableMetricModule.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/api/FakeBigtableConnection.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/api/Mutations.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/api/RowFilter.java
- metric/bigtable/src/test/java/com/spotify/heroic/metric/bigtable/BigtableBackendIT.java
- metric/bigtable/src/test/java/com/spotify/heroic/metric/bigtable/api/RowFilterTest.java
- metric/memory/src/main/java/com/spotify/heroic/metric/memory/MemoryBackend.java
- metric/memory/src/test/java/com/spotify/heroic/metric/memory/MemoryBackendIT.java
This introduces a FakeBigtableConnection which can be used to include the majority of the code under `BigtableBackend` under `AbstractMetricBackendIT`.
With this, these tests can be run without operating an external Bigtable cluster, making it suitable for inclusion in the test suites that are automatically run on every PR.
> Introduce FakeBigtableConnection and more test coverage

- heroic-component/src/main/java/com/spotify/heroic/querylogging/QueryContext.java
- heroic-component/src/main/java/com/spotify/heroic/querylogging/QueryLogger.java
- heroic-core/src/main/java/com/spotify/heroic/http/query/QueryResource.java
- heroic-core/src/main/java/com/spotify/heroic/querylogging/Slf4jQueryLogger.java
- heroic-core/src/main/java/com/spotify/heroic/querylogging/noop/NoopQueryLogger.java
- heroic-core/src/test/java/com/spotify/heroic/querylogging/Slf4jQueryLoggerTest.java
- tools/querylog_mappings.yaml
httpContext contains information about the http connection from where the query
originated from. It was previously only logged for the 'http-query-*' query
types. It's now added to all types so that the information is always available
for filtering in kibana.
> [component, core] Add httpContext to all query log types

- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/AbstractElasticsearchMetadataBackend.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/Connection.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/index/IndexMapping.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/index/RotatingIndexMapping.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/index/SingleIndexMapping.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendV1.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/SuggestBackendKV.java
The first commit fixes a bug, which prevents Heroic from loading historical data, when querying with an absolute range in the past.
The two following commits just cleans up the API.
> [Metadata] Pick the correct indexes

- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/Connection.java
- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/ConsumerThread.java
- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/ConsumerThreadCoordinator.java
- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/KafkaConsumer.java
- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/KafkaConsumerModule.java
- heroic-component/src/main/java/com/spotify/heroic/consumer/ConsumerSchema.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopConsumerReporter.java
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/Spotify100.java
- heroic-core/src/main/java/com/spotify/heroic/ingestion/CoreIngestionGroup.java
- heroic-core/src/test/java/com/spotify/heroic/ingestion/CoreIngestionGroupTest.java
- heroic-dist/src/test/java/com/spotify/heroic/HeroicConfigurationTest.java
- heroic-dist/src/test/resources/heroic-all.yml
- heroic-dist/src/test/resources/heroic-kafka.yml
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticConsumerReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticHeroicTimerGauge.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SimpleGauge.java
Ensure safe Kafka consumption by disabling Kafka auto-commit and instead
explicitly commiting for data that we know has been completely written
to backend.
More specifically, we periodically pause consumption, wait for all
outstanding backend write requests to complete, then commit Kafka
offsets.
> [heroic] Transactional Kafka consumer

- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/ConsumerThread.java
- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/KafkaConsumerModule.java
- heroic-component/src/main/java/com/spotify/heroic/common/DateRange.java
- heroic-component/src/main/java/com/spotify/heroic/dagger/LoadingComponent.java
- heroic-component/src/main/java/com/spotify/heroic/time/Clock.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-core/src/main/java/com/spotify/heroic/cluster/NodeRegistry.java
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/Spotify100.java
- heroic-core/src/main/java/com/spotify/heroic/http/metadata/MetadataResource.java
- heroic-core/src/main/java/com/spotify/heroic/shell/Tasks.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/Fetch.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/LoadGenerated.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/MetadataLoad.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/MetadataWrite.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/ParseQuery.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/SuggestPerformance.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/Write.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/WritePerformance.java
- heroic-core/src/test/java/com/spotify/heroic/CoreQueryManagerTest.java
- heroic-loading/src/main/java/com/spotify/heroic/dagger/LoadingModule.java
hardcoded `System.currentTimeMillis()` calls (and the like) are hard to test.
This introduces an interface `com.spotify.heroic.time.Clock` that should be dependency injected instead of making use of the static methods.
Most call sites are also fixed in a separate commit, except a few harder ones.
> Introduce indirection for accessing the system clock

- repackaged/bigtable/pom.xml
Note by @udoprog: fixed the branch (2017-03-10)
> [repackaged] use os.detected.classifier from os-maven-plugin

- heroic-component/src/main/java/com/spotify/heroic/common/Feature.java
- heroic-component/src/main/java/com/spotify/heroic/metric/FetchData.java
- heroic-component/src/main/java/com/spotify/heroic/metric/FullQuery.java
- heroic-component/src/main/java/com/spotify/heroic/metric/MetricBackend.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/Fetch.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/Query.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/WritePerformance.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractClusterQueryIT.java
- heroic-test-it/src/main/java/com/spotify/heroic/test/AbstractMetricBackendIT.java
- metric/bigtable/src/main/java/com/spotify/heroic/analytics/bigtable/BigtableAnalyticsMetricBackend.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableBackend.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/api/ReadRowRangeRequest.java
- metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/DatastaxBackend.java
- metric/memory/src/main/java/com/spotify/heroic/metric/memory/MemoryBackend.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetricBackendReporter.java
When reading data from MetricBackend, allow different series to be consumed continuously (in a streaming fashion) which in many cases reduces the amount of memory that must be retained.
When this is merged, there are two more possible pending changes queued up, based on this:
* jo-ri#2: Allow a single row to be read in chunks
* jo-ri#3: Use the protobuf client
(Originally all three steps were in PR #181)
> Read data from MetricBackend continuously

- heroic-component/src/main/java/com/spotify/heroic/aggregation/DistributedAggregationCombiner.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
This patch is attempting to make sure that queries containing a delta aggregation still returns a meaningful cadence.
> [Aggregation] Make sure that aggregation cadence is not lost in distributed reduction.

- heroic-dist/pom.xml
- pom.xml
This enables logging for any component that uses `org.apache.common.logging` for logging.
> [dist] enable jcl-over-slf4j

- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/ConsumerThread.java
- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/KafkaConsumerModule.java
The Kafka consumer timeout is actually not needed, just adds complexity. So simplify by disabling the timeout and removing the code that handles the timeout.
> [consumer/kafka] Disable Kafka consumer timeout

- heroic-core/src/main/java/com/spotify/heroic/cluster/CoreClusterManager.java
- rpc/grpc/src/main/java/com/spotify/heroic/rpc/grpc/GrpcRpcProtocol.java
This causes the client side to accumulate established connections if metadata refresh fails on the remote side for any reason.
The channels are probably not closed through gc because they are associated with persistent event loop groups when created.
This has been tested by intentionally breaking the metadata handle on the remote end.
> [core,rpc/grpc] close channel if initial metadata refresh fails

- discovery/simple/src/main/java/com/spotify/heroic/cluster/discovery/simple/StaticListDiscovery.java
- discovery/simple/src/main/java/com/spotify/heroic/cluster/discovery/simple/StaticListDiscoveryModule.java
- heroic-all/src/main/java/com/spotify/heroic/profile/ClusterProfile.java
- heroic-component/src/main/java/com/spotify/heroic/cluster/ClusterDiscovery.java
- heroic-core/src/main/java/com/spotify/heroic/cluster/ClusterManagerModule.java
- heroic-core/src/main/java/com/spotify/heroic/cluster/CoreClusterManager.java
- heroic-core/src/main/java/com/spotify/heroic/cluster/NodeRegistry.java
- heroic-core/src/test/java/com/spotify/heroic/cluster/CoreClusterManagerTest.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractLocalClusterIT.java
This requires configuration - reusing the already existing 'topology'
configuration variable. Use it to specify which shards that are
expected to exist / be represented by nodes in the cluster. If Heroic
at some point has zero known nodes for any of these shards that will
be treated as a shard error and shown in query responses in the form
of entries in the 'errors' hash.
The list of expected shards is optional, but can be specified as so:
```
cluster:
tags:
site: site2
part: a
discovery:
type: ...
topology:
- site: site1
- site: site2
part: a
- site: site2
part: b
- site: site3
```
> [all] A shard with no discovered nodes is an error

- heroic-component/src/main/java/com/spotify/heroic/aggregation/BucketAggregationInstance.java
- heroic-component/src/test/java/com/spotify/heroic/aggregation/BucketAggregationTest.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractClusterQueryIT.java
This modifies bucket aggregations so that they don't include the first bucket in the range since it
will never be provided data due to how it is queried. Data fetches are performed in the range
`(start - extent, start]`, but buckets are setup in the range `[start, end]` with size being used as
a distance between buckets.
Since the bucket selection algorithm needed to change because of this, it was simplified and test
cases added to clarify how it works.
> [component] fix sampling in bucket aggregations

- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/DeltaInstance.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/FilterAggregation.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/MetricMappingAggregation.java
- heroic-component/src/main/java/com/spotify/heroic/QueryOptions.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/AggregationInstance.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/BucketAggregationInstance.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/BucketStrategy.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/ChainInstance.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/DistributedAggregationCombiner.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/EmptyInstance.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/GroupingAggregation.java
- heroic-component/src/main/java/com/spotify/heroic/common/Feature.java
- heroic-component/src/main/java/com/spotify/heroic/common/Features.java
- heroic-component/src/test/java/com/spotify/heroic/aggregation/BucketAggregationTest.java
- heroic-component/src/test/java/com/spotify/heroic/aggregation/BucketStrategyTest.java
- heroic-component/src/test/java/com/spotify/heroic/aggregation/GroupingAggregationTest.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
This moves the specific implementation for how a bucket strategy is performed into the `BucketStrategy` interface.
This is intended to set us up so that we can eventually switch from the current `(end - extent, end]` (`BucketStrategy.END`) bucket interval, to `[start, start + extent)` (`BucketStrategy.START`).
To maintain backwards compatibility when the alternative implementation is introduced, a new feature (`com.spotify.heroic.end_bucket_strategy`) is introduced and enabled by default.
> [aggregation/simple,component,core] introduce BucketStrategy

- heroic-core/src/main/java/com/spotify/heroic/cluster/CoreClusterManager.java
When the cluster manager refreshes the cluster regularly, it will notice
if a node is down and remove it from the list of active nodes. This
works well. However, this commit ensures that the channel (containing
the actual tcp/ip connection) is also really closed. This fixes a
resource leak where sockets would not be closed.
> [core] Explicitly close connection for failed nodes

- heroic-core/src/main/java/com/spotify/heroic/cluster/CoreClusterManager.java
Existing nodes that hadn't changed were logged as 'new', and new nodes
weren't logged at all.
> [core] Correct logging of cluster update (& less verbose)

- heroic-component/src/main/java/com/spotify/heroic/cluster/ClusterShard.java
- heroic-component/src/main/java/com/spotify/heroic/metric/RuntimeNodeException.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/HeroicReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/QueryReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopHeroicReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopQueryReporter.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-core/src/main/java/com/spotify/heroic/QueryModule.java
- heroic-core/src/main/java/com/spotify/heroic/cluster/ClusterManagerModule.java
- heroic-core/src/main/java/com/spotify/heroic/cluster/CoreClusterManager.java
- heroic-core/src/test/java/com/spotify/heroic/CoreQueryManagerTest.java
- heroic-core/src/test/java/com/spotify/heroic/cluster/CoreClusterManagerTest.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticHeroicReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticQueryReporter.java
Sometimes an RPC call to a node in the cluster may be cancelled. This
used to cause the whole query to be cancelled. This PR does two things:
* Adds metrics so that we know how often RPC calls gets errors and cancellations
* Now Heroic simply retries with the next node in the shard, when an RPC call was cancelled.
Possibly, the metrics should have their own reporter. However, I chose to put them in the same as the query metrics now, since it's quite related.
> Recover from RPC cancellation

- heroic-core/src/main/java/com/spotify/heroic/cluster/CoreClusterManager.java
- rpc/grpc/src/main/java/com/spotify/heroic/rpc/grpc/GrpcRpcProtocol.java
RPC calls that get cancelled unexpectedly should be handled. These commits make them be handled in a similar way as errors. Thus a cancelled 'metadata' RPC call in the cluster refresh will cause the node to be removed from the list of active nodes. Similarly for a cancelled initial 'metadata' RPC call directly after connect.
This also makes the grpc layer close the channel if the initial metadata RPC call is cancelled, just like it already does for errors. Potentially, this would otherwise be a rare tcp/ip socket leak.
> Handle RPC cancellations

- heroic-component/src/main/java/com/spotify/heroic/metric/FetchQuotaWatcher.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/DataInMemoryReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopMetricBackendReporter.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableBackend.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetricBackendReporter.java
* query-metrics-samples-read - Per-query histogram of number of samples
read from metric backend on data-node
* query-metrics-rows-accessed - Per-query histogram of number of rows in
metric backend that was accessed on data-node. Can give an additional
indication of the load that the query put on the backend.
> Add metrics for metric backend reads

- heroic-component/src/main/java/com/spotify/heroic/metric/QueryMetricsResponse.java
- heroic-core/src/main/java/com/spotify/heroic/http/query/QueryResource.java
- heroic-core/src/test/java/com/spotify/heroic/metric/BasicSerializationTest.java
- heroic-core/src/test/resources/com/spotify/heroic/metric/QueryMetricsResponse.json
- tools/querylog_mappings.yaml
Expose in query response and query log a measurement of how many data points that were read from the metric backend. The measurement is done before aggregations etc, so gives an indication of how much load the query put on the metric backend.
> [component,core,tools] Add rawSampleSize in query log

- heroic-core/src/main/java/com/spotify/heroic/cluster/TracingClusterNode.java
This fixes a regression where the node name went missing in the
error field in the query response. Instead of a node name the
wrapper TracingClusterNode was shown. This commit fixes that.
> [core] Fix query error output of node name

- heroic-dist/src/main/java/com/spotify/heroic/HeroicService.java
Correct parameter in HeroicService help
documentation #277 (use -P instead of -p)
in 'Available profiles' secton
> [dist] Fix HeroicService param in help doc

- repackaged/bigtable/pom.xml
> Revert "[bigtable] Bump client version to 0.9.6.2"

- metric/bigtable/pom.xml
- metric/bigtable/src/main/java/com/spotify/heroic/analytics/bigtable/BigtableAnalyticsModule.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableConnectionBuilder.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableMetricModule.java
- pom.xml
- repackaged/bigtable/pom.xml
- rpc/grpc/pom.xml
Upgrade bigtable client to 0.9.6.2, which requires updated grpc, which requires updated netty.
> Bigtable / grpc / netty, version bumps

- heroic-core/src/main/java/com/spotify/heroic/http/HttpServer.java
Enabling gzip for responses from POST endpoints that serve JSON (e.g. `/query/metrics` and `/query/batch`) has a significant benefit when requesting large amounts of data. I chose 860 bytes for the minimum gzip size since that is the default that Akamai uses for their gzip threshold.
> [heroic-core] enable gzip

- metric/datastax/pom.xml
- pom.xml
- repackaged/datastax/pom.xml
NOTE: You need to re-run ./tools/install-repackaged after this commit.
* Upgrades Datastax driver to 3.2.0
* Isolates the Datastax driver so that its dependencies doesn't clash
with other Heroic dependencies.
> [datastax] Upgrade & repackage Datastax driver

- rpc/grpc/src/main/java/com/spotify/heroic/rpc/grpc/GrpcRpcProtocol.java
There was already an option maxFrameSize in the Grpc module, but it
wasn't being honoured. Now it is.
> [rpc/grpc] Actually use maxFrameSize option

- heroic-component/src/main/java/com/spotify/heroic/common/Histogram.java
- heroic-component/src/main/java/com/spotify/heroic/metric/FullQuery.java
- heroic-component/src/main/java/com/spotify/heroic/metric/MetricCollection.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/DataInMemoryReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/QueryReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopMetricBackendReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopQueryReporter.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
- heroic-core/src/test/java/com/spotify/heroic/metric/BasicSerializationTest.java
- heroic-core/src/test/java/com/spotify/heroic/querylogging/Slf4jQueryLoggerTest.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableBackend.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetricBackendReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticQueryReporter.java
query-metrics-max-live-samples - Maximum amount of data points in memory
at any time for a query.
query-sample-latency - Effectively the latency of 1 sample read. This
makes for a latency measurement that is comparable across queries. This
can be used to show if any query loaded the system more than what would
have been expected from just the number of samples.
> Add metrics for measuring query load

- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/Module.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/StripedSum2Bucket.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/Sum2.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/Sum2Bucket.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/Sum2Instance.java
- aggregation/simple/src/test/java/com/spotify/heroic/aggregation/simple/Sum2BucketTest.java
I noticed that the `spread` aggregator includes `sum2` (sum of squares), which we are using for standard deviation calculations. I am proposing that `sum2` be made into a first-class aggregation (along with min, max, count, sum, etc.) It's a small, isolated change. Tested and working in our QA cluster.
> [aggregation] sum squared

- consumer/kafka/src/main/java/com/spotify/heroic/consumer/kafka/ConsumerThread.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/ConsumerReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopConsumerReporter.java
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/Spotify100.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticConsumerReporter.java
A message with timestamp <= 0 currently causes infinite retries in the consumer. Let's check explicitly for that case and fail with a schema validation error so that the message is dropped.
Also adds a new metric 'message-retry' that indicates message consumption retries.
> Consumer: Handle messages with invalid timestamp

- heroic-component/src/main/java/com/spotify/heroic/statistics/DataInMemoryReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopMetricBackendReporter.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetricBackendReporter.java
Renamed metric:
query-metrics-row-density -> query-metrics-row-metric-distance
This metric existed but actually measured the distance between metrics,
instead of the density. Now renamed. Measurement is average ms between
samples.
New metric:
query-metrics-row-density
Actually measure the density of read data. Measurement is average
number of samples per million seconds. The slightly awkward prefix is
due to floating numbers not being supported in histograms.
> New metric for data density of reads

- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableBackend.java
Enforce execution order so that rowsAccessed statistic is always updated
before being read.
> [metric/bigtable] Ensure correct statistics

- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
The query log entries for dataDensity was almost always 0 due to wrong
scaling. It's now correctly metrics per million seconds.
> [core] Correct scale for dataDensity query log

- heroic-component/src/main/java/com/spotify/heroic/cluster/ClusterShard.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
When testing a new configuration option, backend type, code change, etc
it can be very good to be able to test with the same query load as your
main production cluster. This commit adds this possibility.
Set magic tag darkload:true on your shard. This will cause queries to
fan out to it, but the result will be discarded.
> [component,core] Add darkload functionality

- heroic-all/src/main/java/com/spotify/heroic/HeroicModules.java
- heroic-component/src/main/java/com/spotify/heroic/conditionalfeatures/ConditionalFeatures.java
- heroic-component/src/main/java/com/spotify/heroic/dagger/PrimaryComponent.java
- heroic-component/src/main/java/com/spotify/heroic/requestcondition/RequestCondition.java
- heroic-core/src/main/java/com/spotify/heroic/HeroicConfig.java
- heroic-core/src/main/java/com/spotify/heroic/HeroicCore.java
- heroic-core/src/main/java/com/spotify/heroic/conditionalfeatures/List.java
- heroic-core/src/main/java/com/spotify/heroic/conditionalfeatures/Match.java
- heroic-core/src/main/java/com/spotify/heroic/conditionalfeatures/Module.java
- heroic-core/src/main/java/com/spotify/heroic/dagger/PrimaryModule.java
- heroic-core/src/main/java/com/spotify/heroic/requestcondition/All.java
- heroic-core/src/main/java/com/spotify/heroic/requestcondition/Any.java
- heroic-core/src/main/java/com/spotify/heroic/requestcondition/ClientId.java
- heroic-core/src/main/java/com/spotify/heroic/requestcondition/Module.java
- heroic-core/src/main/java/com/spotify/heroic/requestcondition/Noop.java
- heroic-core/src/main/java/com/spotify/heroic/requestcondition/UserAgent.java
- heroic-core/src/test/java/com/spotify/heroic/requestcondition/RequestConditionTest.java
- heroic-dist/src/test/java/com/spotify/heroic/HeroicConfigurationTest.java
- heroic-dist/src/test/resources/heroic-conditional-features.yml
- heroic-loading/src/main/java/com/spotify/heroic/HeroicMappers.java
This introduces conditional features that can be set in the configuration file like the following:
```yaml
conditionalFeatures:
type: list
list:
- type: match
features:
- com.spotify.heroic.cache_query
condition:
type: clientId
clientId: foobar
- type: match
features:
- com.spotify.heroic.cache_query
condition:
type: any
conditions:
- type: clientId
clientId: foo
- type: clientId
clientId: bar
```
The current implementation permits enabling features depending on [client id](https://github.com/udoprog/heroic/blob/06f8d1e02bc507226a5821ff4f95df0b85311c79/heroic-core/src/main/java/com/spotify/heroic/requestcondition/ClientId.java), or [user agent](https://github.com/udoprog/heroic/blob/06f8d1e02bc507226a5821ff4f95df0b85311c79/heroic-core/src/main/java/com/spotify/heroic/requestcondition/UserA …
> [all] introduce sub-system for conditional features

- heroic-core/src/main/java/com/spotify/heroic/cache/memcached/MemcachedCacheModule.java
Currently `maxTtl` is not being read from configuration file. This fixes that.
> [core] fix maxTtl cache setting

- heroic-component/src/main/java/com/spotify/heroic/metric/CacheInfo.java
- heroic-component/src/main/java/com/spotify/heroic/metric/QueryMetricsResponse.java
- heroic-component/src/main/java/com/spotify/heroic/metric/QueryResult.java
- heroic-core/src/main/java/com/spotify/heroic/cache/memcached/MemcachedQueryCache.java
- heroic-core/src/main/java/com/spotify/heroic/http/query/QueryResource.java
- heroic-core/src/test/java/com/spotify/heroic/metric/BasicSerializationTest.java
- heroic-core/src/test/resources/com/spotify/heroic/metric/QueryMetricsResponse.json
This introduces the `CacheInfo` object as a part of the `QueryMetricsResponse`.
This tells us:
* What the cache key used was.
* What the ttl of the cached item was.
* If a cached result was used, or not.
> [component,core] more detailed caching information

- heroic-component/src/main/java/com/spotify/heroic/statistics/MetadataBackendReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/SuggestBackendReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopMetadataBackendReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopSuggestBackendReporter.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetadataBackendReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticSuggestBackendReporter.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/SuggestBackendKV.java
Renamed write-* group of metrics to cached-write-* for metadata and
suggest. These metrics measure the full set of writes, including the
ones that hit the internal write-cache in these modules, and thus
actually aren't sent to ES.
Added new write-* group of metrics. These measure the actual writes sent
to ES.
> [metadata,suggest] Metrics for actual writes

- pom.xml
- statistics/semantic/pom.xml
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/HistogramBuilder.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/MinMaxSlidingTimeReservoir.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticConsumerReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetricBackendReporter.java
- statistics/semantic/src/test/java/com/spotify/heroic/statistics/semantic/MinMaxSlidingTimeReservoirIT.java
- statistics/semantic/src/test/java/com/spotify/heroic/statistics/semantic/MinMaxSlidingTimeReservoirTest.java
The common semantic metrics Histogram uses a reservoir that provides statistically relevant data without saving all samples, by performing random sampling. That, however, means that min/max isn't accurate for high-rate metrics.
This commit introduces a new reservoir that can be layered on top of the old one, to keep special track of min/max values.
> Better min/max statistics for high-rate Histograms

- heroic-core/src/main/java/com/spotify/heroic/cache/memcached/MemcachedQueryCache.java
This introduces consistent hashing for queries, the current implementation did not result in consistent results across the same request.
This is accomplished by the introduction of the `ObjectHasher` framework, and a set of `hashTo(..)` methods in relevant classes.
> More changes to improve caching

- heroic-component/src/main/java/com/spotify/heroic/statistics/MetadataBackendReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/SuggestBackendReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopMetadataBackendReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopSuggestBackendReporter.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/AbstractElasticsearchBackend.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/DefaultRateLimitedCache.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/DisabledRateLimitedCache.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/RateLimitedCache.java
- heroic-elasticsearch-utils/src/test/java/com/spotify/heroic/elasticsearch/index/DefaultRateLimitedCacheTest.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetadataBackendReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticSuggestBackendReporter.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/SuggestBackendKV.java
write-* - the full set of write requests coming to metadata/suggest BE
writes-dropped-by-cache-hit - writes dropped by the write cache
backend-write-* - the write requests that are actually sent to ES
writes-dropped-by-rate-limit - write requests where ES says the document
already existed.
> [metadata,suggest] Rework write metrics

- heroic-component/src/main/java/com/spotify/heroic/filter/AndFilter.java
- heroic-component/src/main/java/com/spotify/heroic/filter/FalseFilter.java
- heroic-component/src/main/java/com/spotify/heroic/filter/FilterUtils.java
- heroic-component/src/main/java/com/spotify/heroic/filter/HasTagFilter.java
- heroic-component/src/main/java/com/spotify/heroic/filter/MatchKeyFilter.java
- heroic-component/src/main/java/com/spotify/heroic/filter/MatchTagFilter.java
- heroic-component/src/main/java/com/spotify/heroic/filter/NotFilter.java
- heroic-component/src/main/java/com/spotify/heroic/filter/OrFilter.java
- heroic-component/src/main/java/com/spotify/heroic/filter/RawFilter.java
- heroic-component/src/main/java/com/spotify/heroic/filter/RegexFilter.java
- heroic-component/src/main/java/com/spotify/heroic/filter/StartsWithFilter.java
- heroic-component/src/main/java/com/spotify/heroic/filter/TrueFilter.java
- heroic-component/src/test/java/com/spotify/heroic/filter/FilterTest.java
- heroic-core/src/test/java/com/spotify/heroic/filter/FilterSerializerTest.java
- heroic-loading/src/main/java/com/spotify/heroic/filter/CoreFilterModifier.java
- heroic-loading/src/main/java/com/spotify/heroic/filter/FilterRegistry.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/SuggestBackendKV.java
This commit adds object-based deserialization for filters.
Object-based deserialization emulates Jackson's type-based serialization, by allowing the following kind of objects to be accepted as filters (these two are now equivalent):
```json
["=", "foo", "bar"]
{"type": "matchTag", "tag": "foo", "value": "bar"}
```
The reason behind doing this is to better support static languages, and their corresponding serialization frameworks. While it is very common to immediately support the second variant, the first one is not.
> [all] provide object-based deserialization for filters

- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/DeltaInstance.java
When using distributed aggregations, a delta aggregation were combining the data with a second delta aggregation, causing inaccurate result.
> [aggregation] Fix Delta aggregation with dist agg

- metric/bigtable/pom.xml
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableConnectionBuilder.java
- repackaged/bigtable/pom.xml
- rpc/grpc/pom.xml
Revert the BT client library from 0.9.7.1 to 0.9.6.2, because of a known issue in 0.9.7.1. Version 1.0.0 will have the fix, but is not out yet.
> Back to bt 0.9.6.2

- heroic-component/src/main/java/com/spotify/heroic/common/Features.java
- heroic-component/src/main/java/com/spotify/heroic/metric/MetricBackend.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/Fetch.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractConsumerIT.java
- heroic-dist/src/test/java/com/spotify/heroic/LoggingMetricModule.java
- heroic-test-it/src/main/java/com/spotify/heroic/test/AbstractMetricBackendIT.java
- metric/bigtable/src/main/java/com/spotify/heroic/analytics/bigtable/BigtableAnalyticsMetricBackend.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableBackend.java
- metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/DatastaxBackend.java
- metric/memory/src/main/java/com/spotify/heroic/metric/memory/MemoryBackend.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetricBackendReporter.java
This code path was already marked deprecated before, and was kept
as a safety fallback while adding the sliced fetch support.
Removing this code will make it easier to do future changes.
> Remove non-sliced metric fetch code path

- heroic-component/src/main/java/com/spotify/heroic/statistics/HeroicReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopHeroicReporter.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/DefaultRateLimitedCache.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/DisabledRateLimitedCache.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/RateLimitedCache.java
- heroic-elasticsearch-utils/src/test/java/com/spotify/heroic/elasticsearch/index/DefaultRateLimitedCacheTest.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/ElasticsearchMetadataModule.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticHeroicReporter.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/ElasticsearchSuggestModule.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/SuggestBackendKV.java
This changes the behaviour of the write cache & rate limiter for metadata/suggest consumptiom. It used to drop metadata/suggest ingestion of metrics that went above the rate limit. It will now instead block, causing a queue of metrics to build up if the rate limit is too low.
The upside of this change is that the delay for a new timeseries to show up becomes deterministic - it will take as long as it takes to read through the current queue of metrics. Previously it was a matter of probability.
> Blocking write cache

- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableMetricModule.java
If no credentials is specified, use "default credentials" for Bigtable.
> [bigtable] Use default credentials

- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/DisabledRateLimitedCache.java
- heroic-elasticsearch-utils/src/test/java/com/spotify/heroic/elasticsearch/DefaultRateLimitedCacheTest.java
- heroic-elasticsearch-utils/src/test/java/com/spotify/heroic/elasticsearch/DisabledRateLimitedCacheTest.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/ElasticsearchMetadataModule.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/ElasticsearchSuggestModule.java
The `DisabledRateLimitedCache` was missing metrics around how often it was being hit.
@hexedpackets @jsferrei
> [heroic-elasticsearch-utils] add metrics to DisabledRateLimitedCache

- .gitignore
- heroic-core/src/main/java/com/spotify/heroic/cache/memcached/MemcachedCacheModule.java
- heroic-core/src/main/java/com/spotify/heroic/cache/memcached/MemcachedQueryCache.java
- heroic-elasticsearch-utils/pom.xml
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/DistributedRateLimitedCache.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/MemcachedConnection.java
- heroic-elasticsearch-utils/src/test/java/com/spotify/heroic/elasticsearch/DistributedRateLimitedCacheTest.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/ElasticsearchMetadataModule.java
- pom.xml
- repackaged/folsom/pom.xml
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/ElasticsearchSuggestModule.java
A distributed cache that does not allow to be called more than a specific rate.
Instead of having a cache that is local to each consumer this allows the cache to be distributed to all the instances. This became necessary when migrating from Kafka -> Google PubSub as a consumer with PubSub will not have a stable partition of metrics.
Reads from the distributed cache are stored locally to reduce the load on the distributed cache cluster.
There is a separate commit that updates folsom to the latest stable version.
@hexedpackets @jsferrei @sjoeboo
> [heroic-elasticsearch-utils] add DistributedRateLimitedCache

- consumer/pubsub/src/main/java/com/spotify/heroic/consumer/pubsub/Connection.java
- consumer/pubsub/src/main/java/com/spotify/heroic/consumer/pubsub/PubSubConsumerModule.java
* Change the default number of outstanding messages to 20k.
* Set parallel pull count to the number of configured threads.
throughput improvements of a consumer compared to its peers. 
@sjoeboo @hexedpackets
> [pubsub] consume more messages

- heroic-core/pom.xml
- heroic-core/src/main/java/com/spotify/heroic/http/HttpServer.java
- heroic-core/src/main/java/com/spotify/heroic/http/tracing/OpenCensusApplicationEventListener.java
- heroic-core/src/main/java/com/spotify/heroic/http/tracing/OpenCensusFeature.java
- heroic-core/src/main/java/com/spotify/heroic/http/tracing/OpenCensusUtils.java
- heroic-shell/src/main/java/com/spotify/heroic/shell/QuoteParser.java
- pom.xml
Based on the existing Jersey OpenTracing implementation: https://github.com/eclipse-ee4j/jersey/tree/master/incubator/open-tracing/src/main/java/org/glassfish/jersey/opentracing
> Add HTTP tracing in jersey for incoming requests.

- metadata/elasticsearch/src/main/resources/com.spotify.heroic.metadata.elasticsearch/kv/metadata.json
- suggest/elasticsearch/src/main/resources/com.spotify.heroic.suggest.elasticsearch/kv/series.json
- suggest/elasticsearch/src/main/resources/com.spotify.heroic.suggest.elasticsearch/kv/tag.json
As of ElasticSearch 5.0, elastic has expressed the intention to deprecate the `string` type in favor of two new data types `text` and `keyword`:  https://www.elastic.co/blog/strings-are-dead-long-live-strings
This PR reflects that change by replacing `not_analyzed` strings as `keyword` type, and `analyzed` strings with the `text` type.  It also simplifies the templates a little bit by disabling `_all` at the parent type level since all of the fields had the `include_in_all` parameter set to false.
> Update ElasticSearch Templates to reflect deprecation of "string"

- heroic-dist/src/test/java/com/spotify/heroic/HeroicConfigurationTest.java
- heroic-dist/src/test/resources/heroic-datastax.yml
- metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/DatastaxBackend.java
- metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/DatastaxMetricModule.java
- metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/DatastaxPoolingOptions.java
- metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/ManagedSetupConnection.java
This change set enables the configuration of the [java driver pooling options](https://docs.datastax.com/en/developer/java-driver/3.2/manual/pooling/) during startup.  
A couple of notes: 
- In our case we are very sensitive to data loss, so we wanted to set up a separate logging file that we can parse for alerting/resubmission, hence the additional logging on `DatastaxBackend.java`. We are totally open (and appreciate recommendations) to different approaches for this.
- I will also submit a separate PR to the `site` branch with documentation updates.
> Enable Cassandra Driver Pooling option configuration

- heroic-component/src/main/java/com/spotify/heroic/statistics/MemcachedReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopHeroicReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopMemcachedReporter.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/DistributedRateLimitedCache.java
- heroic-elasticsearch-utils/src/test/java/com/spotify/heroic/elasticsearch/DistributedRateLimitedCacheTest.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/ElasticsearchMetadataModule.java
- pom.xml
- repackaged/folsom/pom.xml
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticHeroicReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMemcachedReporter.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/ElasticsearchSuggestModule.java
@dmichel1 I'm going to run some quick tests on this first but https://github.com/spotify/folsom/issues/103 has been fixed  in 1.2.1
> Bump folsom to 1.2.1 as it fixes a connection leak

- .scripts/trigger_docker_hub.sh
- .travis.yml
This change allows for a few things: 
* Travis will get triggered on tags matching master-* as well as master.
* Travis will trigger a Docker image build on Docker Hub *only* from tags (releases)
* Travis will send the tag to Docker Hub so the resulting image is tagged the same.
> add tag to trigger for docker hub

- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/ElasticsearchMetadataModule.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/ElasticsearchSuggestModule.java
Allows for the configuration of a max size for the guava cache. Also allows for changing the default concurrency level for the same cache.
* distributedCacheMaxSize (defaults to 30,000,000)
* distributedCacheConcurrency (defaults to 4)
> [metadata|suggest] set a default max size on cache

- heroic-core/pom.xml
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/Spotify100.java
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/Spotify100Proto.java
- heroic-core/src/main/proto/spotify_100.proto
- heroic-core/src/test/java/com/spotify/heroic/consumer/schemas/Spotify100ProtoTest.java
Two commits.
1. Add protobuf schema for ingesting metrics.
2. deprecate host field in json schema since host is now just another tag in heroic. 
@jsferrei @lmuhlha @sjoeboo
> add protobuf schema; deprecate host field

- docs/heroic_consumer_pubsub_local_debug.yml
- heroic-core/pom.xml
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/Spotify100Proto.java
- heroic-core/src/main/proto/spotify_100.proto
- heroic-core/src/test/java/com/spotify/heroic/consumer/schemas/Spotify100ProtoTest.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/DistributedRateLimitedCache.java
- pom.xml
When rolling this out we may need to tweak both the publisher (ffwd) and consumer (heroic) batch settings. With the consumer we may want to reduce the maxOutstandingElement count since a single pubsub message can now contain up to 10,000 metrics with the default ffwd batch settings.
This goes along with https://github.com/spotify/ffwd/pull/99.
@hexedpackets
> [core] modify proto schema to accept compressed batches

- pom.xml
- statistics/semantic/pom.xml
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/HistogramBuilder.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/MinMaxSlidingTimeReservoir.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticAnalyticsReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticConsumerReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticFutureReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticIngestionManagerReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMemcachedReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetadataBackendReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticQueryReporter.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticSuggestBackendReporter.java
- statistics/semantic/src/test/java/com/spotify/heroic/statistics/semantic/MinMaxSlidingTimeReservoirIT.java
- statistics/semantic/src/test/java/com/spotify/heroic/statistics/semantic/MinMaxSlidingTimeReservoirTest.java
We've found meters to be difficult for people to understand, in particular the difficulties around aggregating the results tends to be hard to explain. Using counters and calculating aggregated rates from the raw counts is more aligned with how people intuitively understand the metrics.
This will be a breaking change as far as our graphs and monitoring go. I'd like to get it merged in but wait to release it until we're ready to cut a major version.
> Update semantic-metrics and replace meters with counters

- heroic-shell/src/main/java/com/spotify/heroic/shell/RemoteCoreInterface.java
- pom.xml
There seems to be a bug in 2.19.1 of these plugins causing the integration-test phase to fail with a JVM crash, even with all tests passing.
> Upgrade surefire and failsafe plugins.

- .github/stale.yml
Enables [the stale bot](https://github.com/probot/stale) to close out issues/PRs that haven't had activity for a long time. I set the thresholds kind of arbitrarily, happy to adjust them if anyone has an opinion.
> Enable stale issue bot.

- heroic-dist/build.gradle
Otherwise at runtime you will encounter a `java.lang.ArrayIndexOutOfBoundsException` when loading `org.eclipse.jetty.http.PreEncodedHttpField`
@hexedpackets @lmuhlha @sjoeboo
> [heroic-dist] include http fields in shaded jar

- example/heroic.example.yml
- heroic-core/src/main/java/com/spotify/heroic/HeroicCore.java
Either a collectorHost or grpcCollectorTarget should be defined not both. If a collectorHost is defined it will take priority.
Also make it possible to configure the componentName to allow for different instances of heroic to be running. e.g. production vs staging
@lmuhlha @hexedpackets
> [core] fix tracing configuration

- README.md
Removing the IRC and gitter links since they aren't actively monitored.
> Remove chat links from README

- .travis.yml
- docs/content/_docs/config/elasticsearch_connection.html
- example/heroic.example.yml
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/ConnectionModule.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/TransportClientSetup.java
Currently, heroic is deployed internally with the list of seeds being all the data nodes.
During an incident when capacity was added to an already "red" cluster, puppet modified the heroic config with the new data nodes, and restarted the api. The API was never able to be successfully started bringing down everything.
This change will allow us to have the master nodes that rarely change become the seeds and the data nodes "sniffed" out. Sniffing is disabled by default and will have to be explicitly enabled. If enabled new nodes will be polled for by default every 30 seconds.
https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html
@lmuhlha @hexedpackets @sjoeboo
> [elasticsearch-utils] enable dynamic lookup of nodes

- docs/content/_docs/config/elasticsearch_connection.html
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/ConnectionModule.java
None of these parameters are ever used nor can they be configured via the heroic config.
@spotify/layer8
> [elasticsearch-utils] remove unused parameters

- build.gradle
- debian/rules.in
Building the debian package was failing because gradle couldn't locate the repackaged jars
that get installed in a local m2 repo.
Then the dh_install process couldn't find the build artifacts because the directory name was changed
```
dh_install
cp: cannot stat ‘debian-build/tmp/build/heroic-0.9.0’: No such file or directory
dh_install: cp -a debian-build/tmp/build/heroic-0.9.0 debian-build/heroic-0.9.0/usr/bin/ returned exit code 1
make: *** [binary] Error 2
dpkg-buildpackage: error: debian-build/rules binary gave error exit status 2
```
> [debian] fix build process

- codecov.yml
This disables the commit status checks from codecov. The report will still be added as a comment to PRs, but the PR won't be marked as errored due to coverage.
> Disable codecov status checks.

- docs/content/_docs/query_language.html
The [RegEx filter](https://github.com/spotify/heroic/blob/master/heroic-component/src/main/java/com/spotify/heroic/filter/RegexFilter.java) has existed for a while but as noted in #444 it was never documented.
> Add regex syntax to filter documentation.

- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticStatisticsModule.java
Otherwise when we are running heroic on k8s we won't have CPU metrics since internally kube-state-metrics aren't published to our external monitoring provider.
> [statistics] add jvm cpu metrics

- build.gradle
- docs/content/_docs/config.md
- heroic-core/build.gradle
- heroic-core/src/main/java/com/spotify/heroic/HeroicCore.java
- heroic-core/src/main/java/com/spotify/heroic/http/tracing/OpenCensusApplicationEventListener.java
The latest version of opencensus has a fix to control how much memory can be used for spans.
Also switch over transport to the satellites to okhttp instead of grpc.
@lmuhlha
> [tracing] update opencensus

- run-heroic.sh
Not sure when this happened, but the current revision of the openjdk:8 container in docker hub removed the link to the java executable in `/usr/bin`:
```
$ docker run -it openjdk:8 bash
root@6a2961fa7d6f:/# which java
/usr/local/openjdk-8/bin/java
root@6a2961fa7d6f:/# ls -l /usr/bin/java
ls: cannot access '/usr/bin/java': No such file or directory
root@6a2961fa7d6f:/# echo $PATH
/usr/local/openjdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@6a2961fa7d6f:/# exit
```
As a result, `run-heroic.sh` would fail in any recently built container :(
> fix path to java executable in the openjdk:8 container

- .scripts/trigger_docker_hub.sh
- .travis.yml
Instead of having travis trigger a dockerhub build, github has been configured to send a webhook to dockerhub to  build the image. Dockerhub will build the master branch and any tags and label the docker image appropriately.
> Use new dockerhub build process

- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/Spotify100Proto.java
- heroic-core/src/test/java/com/spotify/heroic/consumer/schemas/Spotify100ProtoTest.java
This was supposed to be a null check like the previous schema however with protobuf the key can never be null. The default value for a string in proto is `""` which was making `isEmpty()` be true.
> [core] allow metric key to be an empty string

- README.md
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/api/Mutations.java
Fixing cell timestamp to be used by BigTable built-in garbage collection.
> Explicitly setting cell timestamp

- .dockerignore
- Dockerfile
- example/heroic.example.yml
- Fix the cache example config
- Add an entrypoint to the docker image. Right now, trying to run the command in the README for Docker will just start a bash shell
> Fix a couple of issues with Heroic minimal setup

- build.gradle
- metric/bigtable/build.gradle
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/credentials/ComputeEngineCredentialsBuilder.java
Newer bigtable versions have upgraded their guava dependency. This resolves #553
> [bigtable] Upgrade bigtable-client-core library.

- heroic-component/src/main/java/com/spotify/heroic/common/Series.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/AnalyticsDumpFetchSeries.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/MetadataEntries.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/MetadataFindSeries.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/SuggestBackendKV.java
generateHash takes into account tags but not resource identifiers, so series with different resource identifiers end up looking the same. This leads to alerts not matching up and getting resolved properly, etc. 
Need to take the resource identifiers into account to remediate this issue, and keep a tag-only version for metadata/suggest cache matching.
> Take resource tags into account when generating the hash code

- build.gradle
- heroic-core/build.gradle
With java11 this library is no longer included and needs to be explicitly added
> [core] add jaxb-api

- build.gradle
Without the pinning, version 1.47 was being used which is incompatible. It uses an experimental method in grpc-core that doesn't exist before 1.20 (we're on 1.16.1) and causes the PubSub client to break.
> Pin version of gax.

- docs/content/_docs/config.md
- heroic-component/src/main/java/com/spotify/heroic/tracing/TracingConfig.kt
- heroic-core/src/main/java/com/spotify/heroic/HeroicConfig.java
- heroic-core/src/main/java/com/spotify/heroic/HeroicCore.java
- heroic-core/src/main/java/com/spotify/heroic/http/HttpServer.java
- heroic-core/src/main/java/com/spotify/heroic/http/HttpServerModule.java
- heroic-core/src/main/java/com/spotify/heroic/http/tracing/OpenCensusApplicationEventListener.java
- heroic-core/src/main/java/com/spotify/heroic/http/tracing/OpenCensusFeature.java
- heroic-core/src/main/java/com/spotify/heroic/http/tracing/OpenCensusUtils.java
* the version tag is now a tag on a trace.
* configure which request headers should be tags via `requestHeadersToTags` rather than adding all the headers.
* moved the tracing config to be typed.
> [tracing] add version and only a whitelisted set of request headers

- .dockerignore
- Dockerfile
In #572 we started using the `git` cli to parse the branch/tag and set version information in the build. This broke the Docker build (reported in #577) since the builder image didn't have git installed.
> Add git to the docker build.

- heroic-component/src/main/java/com/spotify/heroic/aggregation/Chain.java
- heroic-component/src/test/java/com/spotify/heroic/aggregation/ChainDeserializeTest.java
- heroic-component/src/test/java/com/spotify/heroic/aggregation/ChainTest.java
Using:
"aggregators": [{"type": "chain", "chain": [{"type": "delta"}, {"type": "sum", "size": "60s"}]}], 
Replicated the error in production. Tested the fix locally with the same query.
> Chain aggregation fix missing type id

- heroic-component/src/main/java/com/spotify/heroic/tracing/EndSpanFutureReporter.java
the message in the throwable can be null.
> [tracing] fix NPE

- tools/querylog
- tools/querylog_mappings.yaml
- tools/requirements.txt
the string type in es7 has been deprecated and has been replaced with keyword.
https://www.elastic.co/blog/strings-are-dead-long-live-strings
> [tools] update query log mapping for es7

- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/DistributedBucketInstance.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/Module.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/RatePerSecond.kt
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/RatePerSecondInstance.kt
- aggregation/simple/src/test/java/com/spotify/heroic/aggregation/simple/RatePerSecondTest.java
- docs/content/_docs/aggregations.html
The rate per second aggregation calculates the rate per second between samples in a given extent.
Rate per second works with sampling. If a queries resolution is 1 minute and points are published every 30s each bucket will contain 2 points. The rate will be calculated by getting the difference between the two points values and dividing them by the time between the points.
Note: at least 2 points are required in order to calculate the rate. Otherwise the previous value is unknown.
It's intended to be used with cumulative counters. It will handle the counters being reset because of restarts, etc.
I reimplemented an earlier pull request #408 that implemented `ratePerSecond` similarly to how `deltaPerSecond` works which does not support sampling the data. I think sampling is a requirement for …
> [aggregation] add ratePerSecond

- build.gradle
- consumer/pubsub/build.gradle
- metric/bigtable/build.gradle
Otherwise when the pubsub connection is setup with SSL there is a run time error. Not quite sure how the dependency tree changed with Netty when the elasticsearch library was updated since the Netty version was always pinned 🤔.
> [pubsub] use latest version of netty-tcnative-boringssl

- build.gradle
This will also improve logging to show pass/fail/skip for tests as they are being run.
> Force tests to always be out of date in gradle.

- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/AbstractElasticsearchMetadataBackend.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/Connection.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/ScrollTransformResult.kt
- heroic-elasticsearch-utils/src/test/java/com/spotify/heroic/elasticsearch/ScrollTransformStreamTest.java
- heroic-elasticsearch-utils/src/test/java/com/spotify/heroic/elasticsearch/ScrollTransformTest.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
The search scroll must be closed when it's no longer needed otherwise elasticsearch will hold onto them until the timeout is reached. In previous versions of elasticsearch the number of scrolls that could be open was unlimited, with ES7 the default is now 500. It can be overriden with `search.max_open_scroll_context`.
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-scroll.html#_clear_scroll_api
> [metadata] clear search scroll when complete

- Dockerfile
- metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/ManagedSetupConnection.java
Updating Datastax caused an incompatibility with dropwizard metrics - we're loading 4.0.2 which removed the JmxReporter class. The test class path for heroic-metric-datastax has dropwizard 3, so unfortunately this wasn't caught through the IT suite.
Resolves #607
> Disable datastax JMX reporting.

- build.gradle
- docs/content/_docs/config.md
- heroic-component/src/main/java/com/spotify/heroic/tracing/TracingConfig.kt
- heroic-core/build.gradle
- heroic-core/src/main/java/com/spotify/heroic/HeroicCore.java
By default the trace config will use an empty list for the whitelist, which causes the squashing exporter to simply pass everything through to the delegated handler. As an example, turning it on just for fetchSeries calls would mean adding this to the config:
```yaml
tracing:
squash:
whitelist:
- localMetricsManager.fetchSeries
```
> Add squashing trace exporter.

- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-core/src/main/java/com/spotify/heroic/http/query/QueryResource.java
- heroic-core/src/main/java/com/spotify/heroic/http/tracing/OpenCensusApplicationEventListener.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
I believe this is the final part to close out #505. I also fixed the `findSeries` span so that its end time encompasses the `fetch` child spans.
> Scope request spans so that they link to coreQueryManager.

- docs/content/_docs/config.md
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/AbstractElasticsearchMetadataBackend.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/RestConnection.kt
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/TransportConnection.java
- heroic-test/src/main/java/com/spotify/heroic/test/AbstractMetadataBackendIT.java
- heroic-test/src/test/java/com/spotify/heroic/metadata/elasticsearch/AbstractMetadataBackendKVIT.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/ElasticsearchMetadataModule.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
My refactoring of ES missed adding the timeout for search scroll requests (not the initial search). Without this timeout, any requests that cause more than one page of results silently fail - no errors are returned, but Heroic ends up without any hits. Elasticsearch keeps the scroll context open in this case as well. Since the scroll ID in the second response is empty the code path to clear the search scroll is never hit.
I made scrollSize configurable primarily just so it would be easier to test. Closes #632
> [elasticsearch] Timout fix for multi-page scrolling requests.

- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-core/src/test/java/com/spotify/heroic/CoreQueryManagerTest.java
Now that the http parent is linked to the coreQueryManager.query span these tags are no longer needed.
> [core] remove duplicate query tags

- heroic-component/src/main/java/com/spotify/heroic/QueryBuilder.java
- heroic-component/src/main/java/com/spotify/heroic/metric/QueryTrace.java
The annotation is enough to alert the developer (us) to move away from the deprecated methods.
I tried to spend some time migrating the QueryTrace methods but had a hard time following all the involved code. Since we want to do a heroic release soon this will at least cut down on the amount of logging being done in production internally.
Related to https://github.com/spotify/heroic/issues/638
> [heroic-component] remove warnings around deprecated methods

- heroic-component/src/main/java/com/spotify/heroic/common/Feature.java
- heroic-component/src/main/java/com/spotify/heroic/common/FeatureSet.kt
- heroic-component/src/main/java/com/spotify/heroic/metadata/FindSeries.kt
- heroic-component/src/main/java/com/spotify/heroic/metadata/FindSeriesIds.kt
- heroic-component/src/main/java/com/spotify/heroic/metadata/MetadataBackend.java
- heroic-core/src/main/java/com/spotify/heroic/http/metadata/MetadataQueryBody.kt
- heroic-core/src/main/java/com/spotify/heroic/http/metadata/MetadataResource.java
- heroic-core/src/main/java/com/spotify/heroic/metadata/MetadataBackendGroup.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/MetadataFetch.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/MetadataFindSeries.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/MetadataFindSeriesIds.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/AbstractElasticsearchMetadataBackend.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/SearchTransformResult.kt
- heroic-elasticsearch-utils/src/test/java/com/spotify/heroic/elasticsearch/SearchTransformStreamTest.java
- heroic-elasticsearch-utils/src/test/java/com/spotify/heroic/elasticsearch/SearchTransformTest.java
- heroic-test/src/main/java/com/spotify/heroic/test/AbstractMetadataBackendIT.java
- heroic-test/src/test/java/com/spotify/heroic/metadata/elasticsearch/AbstractMetadataBackendKVIT.java
- heroic-test/src/test/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKVTransportIT.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
- metadata/memory/src/main/java/com/spotify/heroic/metadata/memory/MemoryBackend.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetadataBackendReporter.java
- statistics/semantic/src/test/java/com/spotify/heroic/statistics/semantic/SemanticMetadataBackendReporterTest.java
This adds a new feature, `com.spotify.heroic.metadata.live_cursor`, which changes the behavior of Elasticsearch searches for metadata. When enabled the results will be paginated with a live cursor instead of a snapshotted scroll.
Most likely we want this to be the default behavior, but its disabled by default so we can roll it out and test further.
Closes #636
> [elasticsearch-metadata] Add option for live cursor

- heroic-component/src/main/java/com/spotify/heroic/statistics/MetadataBackendReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopMetadataBackendReporter.java
- heroic-core/src/main/java/com/spotify/heroic/http/write/WriteResource.java
- heroic-core/src/main/java/com/spotify/heroic/ingestion/IngestionManagerImpl.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/AbstractElasticsearchMetadataBackend.java
- heroic-elasticsearch-utils/src/test/java/com/spotify/heroic/elasticsearch/SearchTransformTest.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetadataBackendReporter.java
The `failed-es-shards` metric can be used to track how often an elasticsearch shard fails.
Ideally this metric would be added to an elasticsearch specific metric reporter but that framework doesn't currently exist.
Closes #633
> [metadata] add metric for failed shards

- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
Heroic should not return partial results as it will mislead users and cause false positive alerts.
Now when an elasticsearch shard is completely unavailable (including any replicas) the search will fail.
Heroic will return this failure as part of the response body.
```
"errors": [
{
"type": "shard",
"nodes": [
"LocalClusterNode(localMetadata=NodeMetadata(version=0, id=be4b35e7-df70-48a2-a263-1c201cdc9248, tags={site=foo}, service=ServiceInfo(name=The Heroic Time Series Database, version=0.0.1-SNAPSHOT, id=heroic, commit=ac849fac371ee142394f0f48165ce0d43c5dfb74)))"
],
"shard": {
"site": "guc"
},
"error": "[es01][172.21.0.3:9300][indices:data/read/search], caused by [es01][172.21.0.3:9300][indices:data/read/search], caused by Partial shards failure, caused by [es02][172.21.0.2:9300] Node …
```
> [metadata] do not allow partial results from elasticsearch

- .circleci/config.yml
- .dockerignore
- .gitignore
- docs/content/_docs/config.md
- system-tests/.dockerignore
- system-tests/docker-compose.yml
- system-tests/heroic.yaml
- system-tests/requirements.txt
- system-tests/test_heroic.py
I setup the workflow to run in a nightly job, but while testing I temporarily had an always-run workflow. Here's the output of it: https://circleci.com/workflow-run/fd3d0ff0-fd70-462c-937b-ffdb160db110
I think it makes sense to add this to the normal PR CI. The docker build takes about 6 minutes and could/should replace the Docker Hub build. The docker-compose setup and tests take another ~5 minutes on top of that.
Right now the docker-compose setup runs all possible modules except SRV cluster discovery and memcached for caching. As we add tests we might need to spin up multiple clusters with different configurations, but I think that should be pretty straight forward.
> Run system tests in a docker full environment.

- .circleci/config.yml
- heroic-dist/build.gradle
The shaded jar stomps all over log4j plugins, which is only recently broken because of #653 . The transformation merges the plugins together properly.
Also, the Circle system_test job wasn't using the locally built docker image. It was pulling the latest image from the Docker Hub, which meant that PRs were testing against the code in master instead of the local code.
> Fix log4j in shaded jar

- heroic-test/src/main/java/com/spotify/heroic/test/AbstractMetadataBackendIT.java
- heroic-test/src/test/java/com/spotify/heroic/metadata/elasticsearch/AbstractMetadataBackendKVIT.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
- metadata/elasticsearch/src/main/resources/com.spotify.heroic.metadata.elasticsearch/kv/metadata.json
Adds the hash which was already used as `_id` for elasticsearch, but in an indexed field. This also changes the sort field for searching so it will need to be deployed to consumers before API nodes.
Close #659.
> [elasticsearch-metadata] Add hash to use for sorting.

- docs/content/_docs/overview.html
The original wasn't quite worded clearly. This new version tries to make the focus more broad, to move Spotify from a singular focus, into just one of the community members. It also drops the definite article on problems, since presumably there are problems that Heroic did not address.
> Reword introduction in overview

- build.gradle
Internally we have a need for newer log4j features, specifically EventLookup introduced in https://issues.apache.org/jira/browse/LOG4J2-2807
> bump log4j

- metadata/elasticsearch/src/main/resources/com.spotify.heroic.metadata.elasticsearch/kv/metadata.json
So I'm not 100% on this, but when trying to roll out the hash change the api will throw this error (even after the consumers have been running with the hashes rolled out):
```
"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [hash] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"Partial shards failure","phase":"query","grouped":true,"failed_shards":[{"","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [hash] in order to load fielddata in memory by uninverting the inverted …
```
> Ensure has has "doc_values": true

- heroic-component/src/main/java/com/spotify/heroic/statistics/MetricBackendReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopMetricBackendReporter.java
- heroic-test/src/main/java/com/spotify/heroic/test/AbstractMetricBackendIT.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableBackend.java
- metric/datastax/src/test/java/com/spotify/heroic/metric/datastax/NextGenDatastaxBackendIT.java
- metric/memory/src/test/java/com/spotify/heroic/metric/memory/MemoryBackendIT.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetricBackendReporter.java
This change will drop metric with row key length longer than 4096 bytes.
It will also create counter metric so we could alert on high numbers.
> Drop metric with row key length bigger then BT limit

- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
- metric/bigtable/src/test/java/com/spotify/heroic/metric/bigtable/BigtableBackendIT.java
- system-tests/docker-compose.yml
This should help understand the behavior of heroic under pressure.
Next step would be to add these stats as Gauges to SemanticRegistry and use them also to reject queries if above global limit.
Currently each query is responsible for exiting in case limits are breached.
> Add total stats across all queries in local manager

- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
Moved the code to remove quota watcher at the beginning of end() method to make sure we cover all queries.
Some failures would be keeping watchers in the hash and skewing global stats.
> Moving quota watcher clean up to cover all queries

- build.gradle
Compilation currently produces these two warnings
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.xbill.DNS.ResolverConfig (file:/Users/samanthanoellef/.gradle/caches/modules-2/files-2.1/dnsjava/dnsjava/2.1.7/a1ed0a251d22bf528cebfafb94c55e6f3f339cf/dnsjava-2.1.7.jar) to method sun.net.dns.ResolverConfiguration.open()
WARNING: Please consider reporting this to the maintainers of org.xbill.DNS.ResolverConfig
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
An illegal reflective access operation has occurred
Illegal reflective access by org.xbill.DNS.ResolverConfig …
```
> Fix reflexive access warnings

- heroic-component/src/main/java/com/spotify/heroic/statistics/MetricBackendReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopMetricBackendReporter.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetricBackendReporter.java
This will allow us to observe the data points via Grafana and also via logs.
The premise of this to identify global limits we could use to protect Heroic from OOMing by rejecting requests in case current global data points are above the limits.
> Add global data points stats

- heroic-dist/src/main/java/com/spotify/heroic/profile/BigtableProfile.java
- metric/bigtable/src/main/java/com/spotify/heroic/analytics/bigtable/BigtableAnalyticsModule.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableConnection.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableConnectionBuilder.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableMetricModule.java
This is required to configure Heroic to use different clusters specifically to separate read and writes after introducing replica.
[App profiles](https://cloud.google.com/bigtable/docs/app-profiles) are used to route clients to different clusters on the same instance. 
Bigtable instances could have multiple clusters.
All tests are successful as well locally verified configuration with and without application `profile` ID.
> Add Bigtable profile to metrics and analytics modules

- heroic-component/src/main/java/com/spotify/heroic/aggregation/AggregationSession.java
- heroic-component/src/main/java/com/spotify/heroic/metric/Distribution.java
- heroic-component/src/main/java/com/spotify/heroic/metric/DistributionPoint.java
- heroic-component/src/main/java/com/spotify/heroic/metric/HeroicDistribution.java
- heroic-component/src/main/java/com/spotify/heroic/metric/MetricCollection.java
- heroic-component/src/main/java/com/spotify/heroic/metric/MetricType.java
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/Spotify100Proto.java
- heroic-core/src/main/proto/spotify_100.proto
- heroic-core/src/test/java/com/spotify/heroic/consumer/schemas/Spotify100ProtoTest.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableBackend.java
This is the first of several PRs  that will add distribution support to heroic.  With Distribution support heroic will be able to provide histogram data based on data distribution. Distribution support will also enable Opencensus metric import. 
This PR  implements Spotify100Proto consumer and BigtableBackend(ingestion).
**What is New:**
1. Spotify100 Proto Consumer:
This PR introduces a new dataPoint type.
```
@AutoValue
public abstract class DistributionPoint implements Metric {
public abstract long getTimestamp();
public abstract Distribution value();
public static DistributionPoint create(final Distribution value, final long timestamp) {
return new AutoValue_DistributionPoint(timestamp, value);
}
@Override
public boolean valid() {
return value().getValue() != null && …
```
> [WIP]Add distribution support to spotify100_proto and BigtableBackend writer

- build.gradle
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/Spotify100.java
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/spotify100/v2/JsonMetric.kt
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/spotify100/v2/Value.java
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/spotify100/v2/ValueDeserializer.java
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/spotify100/v2/ValueSerializer.java
- heroic-dist/build.gradle
- heroic-dist/src/test/java/com/spotify/heroic/AbstractConsumerIT.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractKafkaConsumerIT.java
- heroic-dist/src/test/java/com/spotify/heroic/DataVersion2.kt
- heroic-dist/src/test/java/com/spotify/heroic/HeroicDistributionGenerator.java
- heroic-dist/src/test/java/com/spotify/heroic/PubSubConsumerIT.java
- heroic-dist/src/test/java/com/spotify/heroic/TMetric.kt
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableBackend.java
This PR add distribution support to spotify100 (jsonMetric) and the ability to fetch distribution metric from bigTable.
Spotify100 consumers and ingestion modules should now be able to handle new and old JsonMetric.
For more information please refer to this [issue](https://github.com/spotify/heroic/issues/695)
> [WIP] Add distribution support to spotify100 and the ability to fetch distribution from bigTable. 

- Dockerfile
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
This change moving creation of QuotaWatcher closer to its usage minimizing chance of exceptional exit before it is used.
Wraps main call to try/catch in order to properly clean QuotaWatcher map.
It also uses QuotaWatcher as key in ConcurrentMap.
> Debug QuotaWatchers creation and cleaning

- docs/content/_docs/query_language.html
HQL has been stable for quite some time. Depending on the result of #481, we may decide to replace HQL. But for now it is disingenuous to list it as experimental.
> Remove experimental warning from HQL docs.

- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
Using `total` value to start logging.
Closes: https://github.com/spotify/heroic/issues/715
> Fix logging

- .github/workflows/docker-build.yml
I did this as GitHub actions instead of CircleCI because of how forks are handled. We want tests to run for every PR, regardless of source. We only want these Docker images to be automatically created for PRs originating from this repo, and not for forks. Doing that in CircleCI might be possible, but this way is simpler and has the benefit of building the image in parallel with the tests running in Circle.
Assuming this works well, we might want to also move our Docker Hub build actions to GitHub actions to reduce the number of places that CI is happening.
Closes #716.
> GitHub action workflow to build PRs in Docker images.

- .gitignore
- build.gradle
- checkstyle.xml
- heroic-core/src/main/java/com/spotify/heroic/http/tracing/OpenCensusUtils.java
- heroic-dist/src/main/java/com/spotify/heroic/shell/QuoteParser.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/api/BigtableDataClientImpl.java
***NOTE: this just updates checkstyle from 6.x to 8.x. The major piece of work remaining is to correct all the offending code.***
- I am a heroic dev
- who wants to know precisely what the squad considers legitimate code formatting
- so that when it comes to code review, there is no need for back-and-forth debate as to our coding style
* added checkstyle config for bad indentation
* also upgraded 6.13 → 8.37
- I am a heroic dev
- who wants to know precisely what the squad considers legitimate code formatting
- so that when it comes to code review, there is no need for back-and-forth debate as to our coding style
* added checkstyle config for bad indentation
* also upgraded 6.13 → 8.37
> Codestyle: update from 6.x to 8.x (see precursor #720)

- heroic-component/src/main/java/com/spotify/heroic/aggregation/AggregationCombiner.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/ComputeDistributionStat.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/DistributedAggregationCombiner.java
- heroic-component/src/main/java/com/spotify/heroic/metric/MetricCollection.java
- heroic-core/build.gradle
- heroic-dist/src/test/java/com/spotify/heroic/AbstractClusterQueryIT.java
- heroic-dist/src/test/java/com/spotify/heroic/HeroicDistributionGenerator.java
- heroic-dist/src/test/java/com/spotify/heroic/RandomData.kt
- heroic-dist/src/test/java/com/spotify/heroic/test/Data.java
- heroic-dist/src/test/java/com/spotify/heroic/test/DistributionPoints.java
- metric/bigtable/build.gradle
- rpc/grpc/src/main/java/com/spotify/heroic/rpc/grpc/GrpcRpcClient.java
This PR adds integration test for distributions query.
> Add distribution query integration test. (Part 2 of 2)

- consumer/pubsub/src/main/java/com/spotify/heroic/consumer/pubsub/PubSubConsumer.java
- consumer/pubsub/src/main/java/com/spotify/heroic/consumer/pubsub/Receiver.java
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/Spotify100.java
- heroic-core/src/main/java/com/spotify/heroic/consumer/schemas/Spotify100Proto.java
- heroic-core/src/main/java/com/spotify/heroic/ingestion/CoreIngestionGroup.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
- heroic-core/src/test/java/com/spotify/heroic/consumer/schemas/Spotify100ProtoTest.java
- heroic-core/src/test/java/com/spotify/heroic/ingestion/CoreIngestionGroupTest.java
- heroic-dist/src/test/java/com/spotify/heroic/analytics/bigtable/HeroicMetricsConfigurationTest.java
- heroic-test/src/main/java/com/spotify/heroic/test/AbstractMetricBackendIT.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableBackend.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/api/BigtableDataClientImpl.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/api/BigtableMutatorImpl.java
- metric/bigtable/src/test/java/com/spotify/heroic/metric/bigtable/BigtableBackendIT.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetricBackendReporter.java
- suggest/elasticsearch/src/main/java/com/spotify/heroic/suggest/elasticsearch/SuggestBackendKV.java
This adds error flags and exception messages to the spans for
metadata, suggest, and bigtable writes when the chain of futures
fails. The same exceptions are also logged. Previously some
exceptions, such as grpc errors, could be masked by sl4j settings.
The trace for a metric write was cleaned up to remove several
intermediary spans. These spans did not have useful information and
had no branching paths, so they were just clutter in the overall
trace.
Closes #724.
> Improve tracing and logging for write errors.

- heroic-dist/src/main/java/com/spotify/heroic/profile/ElasticsearchMetadataProfile.java
The `interval` variable in RotatingIndexMapping is now respected if present in configuration. 
Documentation is already up-to-date.
Closes #742.
> include mapping for metadata index interval

- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/TdigestInstance.kt
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/TdigestInstanceUtils.java
- aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/TdigestMergingBucket.kt
- aggregation/simple/src/test/java/com/spotify/heroic/aggregation/simple/TdigestBucketIntegrationTest.java
- aggregation/simple/src/test/java/com/spotify/heroic/aggregation/simple/TdigestBucketTest.java
- aggregation/simple/src/test/java/com/spotify/heroic/aggregation/simple/ValueBucketIntegrationTest.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/AggregationCombiner.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/DistributedAggregationCombiner.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/EmptyInstance.java
- heroic-component/src/main/java/com/spotify/heroic/aggregation/TDigestAggregationCombiner.java
- heroic-component/src/main/java/com/spotify/heroic/metric/DistributionPoint.java
- heroic-component/src/main/java/com/spotify/heroic/metric/DistributionPointDeserialize.java
- heroic-component/src/main/java/com/spotify/heroic/metric/DistributionPointSerializer.java
- heroic-component/src/main/java/com/spotify/heroic/metric/MetricCollection.java
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractClusterQueryIT.java
- heroic-dist/src/test/java/com/spotify/heroic/HeroicDistributionGenerator.java
- heroic-dist/src/test/java/com/spotify/heroic/RandomData.kt
1. Add a new group combiner to handle simple tdigest query
This combiner handles query that doesn't include aggregation clause.
Query will return the record count in each distributionPoint instead of a binary data.
2. Refactor DistributedCombiner. 
3. Add integration test to validate TdigestBucket thread safety
4. Add addition integration test  for tdigest
6. Remove lock free implementation of TdigestBucket .
**Sample Query** : 
1. curl --location --request POST ''http://localhost:8081/query/metrics'' --header 'Content-Type: application/json' --data-raw '{
"source":"distributionPoints", "range": {"type": "relative", "unit": "DAYS", "value": 30},
"filter": ["and", ["=", "run", "17716d49eab"], ["=", "metric_type", "distribution"]]
}'
return datapoint count in each distributionPoint and -1 …
> Add a simple group combiners and additional IT tests. 

- docs/content/_docs/config.md
- heroic-dist/src/main/java/com/spotify/heroic/profile/ElasticsearchMetadataProfile.java
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/index/IndexMapping.kt
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/index/RotatingIndexMapping.kt
- heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/index/SingleIndexMapping.kt
- heroic-elasticsearch-utils/src/test/java/com/spotify/heroic/elasticsearch/index/RotatingIndexMappingTest.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/ElasticsearchMetadataModule.java
- metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java
Introduce support for RotatingIndexMapping to limit the number of elasticsearch metadata indices read based upon the range of a heroic query. If the newly introduced config flag is set to `true`, the number of read indices is dynamically determined based upon the rotation interval and the range of the query.
This PR also makes the non-dynamic `maxReadIndices` configurable so as to properly support `delete`. This variable should be set to the maximum number of queryable indices that could possibly exist in Elasticsearch based upon the rotation interval and ILM policy. 
Closes #745.
> Dynamic Metadata Read Indices 

- heroic-component/src/main/java/com/spotify/heroic/Query.kt
- heroic-component/src/main/java/com/spotify/heroic/QueryBuilder.java
- heroic-component/src/main/java/com/spotify/heroic/grammar/QueryExpression.kt
- heroic-component/src/main/java/com/spotify/heroic/metric/FetchData.kt
- heroic-component/src/main/java/com/spotify/heroic/metric/FullQuery.java
- heroic-component/src/main/java/com/spotify/heroic/metric/QueryMetrics.java
- heroic-component/src/test/java/com/spotify/heroic/grammar/QueryExpressionTest.java
- heroic-core/build.gradle
- heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
- heroic-core/src/main/java/com/spotify/heroic/shell/task/Fetch.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractClusterQueryIT.java
- heroic-dist/src/test/java/com/spotify/heroic/AbstractConsumerIT.java
- metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableBackend.java
- metric/datastax/src/main/java/com/spotify/heroic/metric/datastax/DatastaxBackend.java
- metric/memory/src/main/java/com/spotify/heroic/metric/memory/MemoryBackend.java
`source` was a legacy query option left over from when `events` were partially supported: 
https://github.com/spotify/heroic/commit/bc533078fad161efa76001cdc4f2a6e22dcb88d5#diff-0e5dda61cc1e44c094fed3ce698715de1d3b11747d9f312df0fbf6a52f70f1fcR222
This PR gets rid of source as an input and essentially re-names it to metricType with a few updates.
Since end users don't care about what `metricType` is being used, Distributions can instead set `metricType` based on what aggregation (tdigest) is being used.
> Remove legacy source input, optional metricType query input for testing

- docs/_layouts/api-endpoint.html
- docs/content/_endpoints/post-query-batch.md
- docs/content/_endpoints/post-query-metrics.md
- heroic-core/src/main/java/com/spotify/heroic/http/HttpServer.java
- heroic-core/src/main/java/com/spotify/heroic/servlet/MandatoryClientIdFilter.java
- heroic-core/src/main/java/com/spotify/heroic/servlet/ShutdownFilter.java
- heroic-core/src/main/java/com/spotify/heroic/servlet/SimpleFilter.java
- heroic-core/src/main/java/com/spotify/heroic/ws/MandatoryClientIdErrorMessage.java
- heroic-core/src/test/java/com/spotify/heroic/servlet/MandatoryClientIdFilterTest.java
- system-tests/test_heroic.py
* it now correctly displays a JSON error message when the request is anonymous.
* also refactored MandatoryClientId & Shutdown Filters using the Template Method design pattern as they were
very similar.
Checkout out [the Template Method design pattern](https://refactoring.guru/design-patterns/template-method) before reviewing this PR 👍🏻
> improved Mandatory ID Filter to return info upon rejection

- heroic-component/src/main/java/com/spotify/heroic/common/FailureType.java
- heroic-component/src/main/java/com/spotify/heroic/metric/NodeError.kt
- heroic-component/src/main/java/com/spotify/heroic/metric/RequestError.java
- heroic-component/src/main/java/com/spotify/heroic/metric/ShardError.kt
- heroic-component/src/main/java/com/spotify/heroic/querylogging/QueryLogger.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/MetricBackendReporter.java
- heroic-component/src/main/java/com/spotify/heroic/statistics/noop/NoopMetricBackendReporter.java
- heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java
- heroic-core/src/main/java/com/spotify/heroic/querylogging/Slf4jQueryLogger.java
- heroic-core/src/main/java/com/spotify/heroic/querylogging/noop/NoopQueryLogger.java
- heroic-core/src/main/java/com/spotify/heroic/servlet/MandatoryClientIdFilter.java
- heroic-test/src/main/java/com/spotify/heroic/test/AbstractMetadataBackendIT.java
- statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticMetricBackendReporter.java
- I am a prism engineer
- Who wants to know the impact of his/her changes on our user base
- So that I can put out any fires efficiently, inform the user base if necessary, and protect heroic
- decorate the exception-handling at the API request level: add a check for the Bigtable timeout exception string
- if found, increment the according counter for the request's x-client-id
- if found, emit a log message that details the x-client-id (and the other usual exception info)
nothing unusual. Just added : 
1. [detection logic](https://github.com/spotify/heroic/blob/8f1b4492f56110693e99ddc39d0cb64dde3ed7d9/heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java#L96), 
2. [a new metric e.g. `query-metrics-client-id-count-playerapp-timeout`](https://github.com/spotify/heroic/b …
> Implement metric and log lines when a Bigtable request times out, per x-client-id
